(function(root){
'use strict';
const C={order:['prologue','qujiang','west','palace','ward','granary','arsenal','master','final'],chapters:{},events:{}};
C.initial=()=>({chapter:'prologue',stage:'intro',found:{A:[],B:[]},witness:{},puzzle:{},verdict:{},results:[],anchors:[],drum:{}});
const clue=(id,name,kind,text,extra={})=>({id,name,kind,text,...extra});
C.chapters.prologue={title:'序章 · 东市飞镜案',site:'market',scene:'market',A:'工匠遗落的工具袋',B:'屋脊上的铜镜',witness:'bell',meet:'market',intro:['市门将闭，追捕的脚步却从街尾逼近。','一面铜镜从工匠怀中滑出，照亮了没有人的巷口。'],clues:{A:[clue('badge','旧工匠腰牌','badge','腰牌上的编制查不到。绳孔已经磨圆，不像新刻的假物。',{truth:3,flag:'oldMark'}),clue('brick','烧焦宫砖','brick','砖心仍是朱红，外层烧成了黑色。背面的年号，在新历中空缺。',{truth:3,anchor:'brick'}),clue('plan','受潮建筑图','paper','图上三条水道都往宫城汇集。纸折处比新坊图多出一道城墙。')],B:[clue('mirror','铜镜背齿','mirror','轴孔偏磨，修补过不止一次。至少用了十年；师父却说它造于五年前。',{truth:3}),clue('thread','纸人牵线','rope','纸人只在灯影重叠处像人。牵线延向绸架，并没有第二名逃犯。'),clue('stamp','镜背旧印','badge','这枚印的缺角，与工匠腰牌上的一致。',{truth:1})]},witnessLines:{A:['更夫把翻倒的灯架扶回原位。','他没拿钱。追过来的时候，还一直把镜面朝地。','巡捕看向屋脊。工匠被扣住手腕后，仍试图用脚踢碎那面镜。'],B:['幻术师拾起落在檐角的纸人，背面只留一根牵线。','摊主：绸子可以赔。下回别踩架子，底脚都松了。','他试着把镜面照向屋檐。亮处与暗处之间，多出一道不属于新瓦的烧痕。']},puzzle:{A:{text:'你手中的旧腰牌有缺角方印，受潮建筑图也留下同样的印。应与搭档核对哪项？',options:['镜背旧印与磨损年代','镜面亮度','绸布颜色'],answer:0},B:{text:'铜镜旧印与腰牌吻合；轴孔至少磨损十年，但领用记录写着五年前新制。应如何归档？',options:['保留年代矛盾，附两份拓印','视为工匠记错','重新磨亮镜背'],answer:0}},verdict:['追捕有据，但铜镜来历仍存矛盾','只是疯子偷窃','把腰牌当赃物销毁'],resolution:['巡捕把腰牌和镜背的印拓在同一张纸上。两个缺角重合。','幻术师：镜子先放在你那里。别磨它背面的齿。','巡捕：你也别走远。我还没问完。','一张曲江请帖夹在工匠的旧图里，今晚的画舫正使用这套水戏机关。']};
C.chapters.qujiang={title:'第一案 · 曲江沉月案',site:'boat',scene:'boat',meet:'boat'};
C.chapters.west={title:'第二案 · 西市无首胡旋案',site:'tavern',scene:'tavern',A:'舞台正面与胡鼓',B:'侧席与纱幕后',witness:'incense',meet:'tavern',intro:['胡鼓最后一声落下，纱幕后的舞影仍在旋转。','灯灭。再亮时，观众席一片惊呼：台上那道身影没有头。','巡捕从人群间挤向台前，幻术师却停在侧席。这里看见的轮廓，与正面完全不同。'],clues:{A:[clue('blood','干净的舞台','cloth','台沿没有喷溅血迹。那一道红色只是绸边，不足以支持台上斩首。',{score:2}),clue('drum','胡鼓暗格','drum','鼓皮张得过松。暗格里藏着死者，颈部有勒痕，死亡早于灯灭。',{score:2}),clue('report','未递出的诉纸','paper','舞姬记下数名客人吸香后失去时间感，准备把记录交给官府。')],B:[clue('angle','侧席视线','mirror','从侧席能看见演员藏起的头颈；只有正面能见到“无头”。',{score:2}),clue('screen','纱幕与旋台','cloth','铜镜遮掉上身，纱幕接住反光，旋台让两段轮廓短暂合在一起。'),clue('incense','返魂香残灰','bowl','相同的气味出现在钟楼、大理寺和宫城的更鼓点。',{truth:5,flag:'returnIncense'})]},witnessLines:{A:['侧席客人：我明明看见她低着头，大家却喊没了头。','酒楼主人：灯暗，谁都看不真切。','巡捕把两排座位分别标在纸上，没有让证人互相改口。'],B:['香贩：这批香不是卖给台上的。账都由酒楼结。','幻术师沿送货地址点下三个墨点：钟楼、大理寺、宫城。','三个点，都与更鼓节点重叠。']},puzzle:{A:{text:'请站到能稳定看见“无头”幻象的位置，再向搭档报方位。',options:['正面座席','舞台侧席','后台鼓架'],answer:0},B:{text:'搭档的座席正对纱幕。哪条光路能解释正面无头、侧面完整？',options:['主镜折射经纱幕拼接轮廓','鼓腔发出影子','所有观众同时闭眼'],answer:0}},verdict:['酒楼主人先勒杀藏鼓，再用演员与铜镜掩盖死亡时间','舞姬在台上遭斩首','证据不足，暂缓定案'],resolution:['胡鼓被移走。舞台不再旋转，镜后演员缩在暗处。','返魂香的购入与勒痕证据被一并封存。','地图上留下三个墨点。城里的更鼓声从远处传来。']};
C.chapters.palace={title:'第三案 · 大明宫百烛案',site:'temple',scene:'temple',A:'锁室与焦椅',B:'宫檐天光机关',witness:'bell',meet:'temple',intro:['旧宫区三间锁室，三名官员先后死于火中。','窗纸没有烧穿，案头的文书也完好。只有椅面与死者留下焦痕。','幻术师抬头看向屋顶。正午的光线在檐角停了一瞬。'],clues:{A:[clue('burn','同向灼痕','cloth','三处灼痕都偏向同一侧。火并非从身体内部起。',{score:2}),clue('oil','座椅油脂','bowl','椅缝里有与寻常灯油不同的黏脂，正位于灼痕中心。'),clue('file','删名旧档','paper','三名死者都签过一份删籍文书。档案官家人的姓名被整行刮去。',{truth:3,score:2})],B:[clue('sun','凹面铜镜','mirror','三面凹镜的焦点轮流落在三把椅子上；调镜刻度上有新划痕。',{score:2}),clue('calendar','不合历法的光位','paper','按当前历法，光不该从这个角度入窗。连续刻下的影线却重合。',{truth:5}),clue('ring','识别戒指的机扣','badge','手靠近锁扣时，戒面与凹槽相合。你还没转钥，闩已退了半寸。',{truth:3,flag:'royalRing'})]},witnessLines:{A:['档案官：我只把旧卷翻出来。你们要看哪一页？','他伸出的手指有研磨铜面的细粉。巡捕把删名旧档推到他面前。','对方的手停住了。'],B:['更夫交来昨日的更牌。日期已经改了，星盘上的针仍指向原处。','幻术师在碎瓷内面留下一笔。巡捕把另一半移到窗台。','他们记住两个位置，等下一次更鼓。']},puzzle:{A:{text:'将断裂花瓶的碎片移到窗台，并留一道证物刻痕。更鼓后应该核对什么？',options:['位置与刻痕是否同时复原','只数花瓶个数','擦去编号'],answer:0},B:{text:'碎片上的记号随更鼓进入完整花瓶内部。哪项实验记录成立？',options:['位置复原，经历留下的记号仍在','一切从未发生','有人更换了所有记号'],answer:0}},verdict:['档案官调凹镜聚光，引燃座椅油脂复仇','天火自行选择死者','证据不足，暂缓定案'],resolution:['屋顶的镜片被遮住，案卷写下焦点与油脂的对应位置。','更鼓响后，焦椅恢复完整。墙上的证物编号却仍在。','幻术师把完整的花瓶举到灯下：那笔记号在瓷壁里面。'],after:{TRUTH:8,CHAOS:8}};
C.chapters.ward={title:'第四案 · 永宁坊失踪案',site:'apricot',scene:'apricot',A:'四十七人的户籍',B:'空屋与地下水道',witness:'shrine',meet:'apricot',intro:['一坊门户紧闭，锅中的饭仍温着，屋里却一个人也没有。','户籍上有四十七个名字。巡捕收起簿子，先看灶灰。','幻术师顺着晾衣绳走到墙角，发现绳影落进了实墙。'],clues:{A:[clue('beds','十九处磨损','cloth','床沿、鞋底与灶灰对应的长期用量，只够十九人。',{score:2,truth:3}),clue('ink','相同墨迹','paper','一个月的习字纸，连墨点落下的位置都一样。没有新的一笔。',{score:2,truth:3}),clue('register','四十七人户册','paper','二十八人的户籍笔迹不同，但炭、粮、衣物从未多出他们的用量。')],B:[clue('drain','出城水道','rope','水道沿旧城基穿出城墙，踏痕向外，没有往返押送留下的深痕。',{score:2}),clue('ball','没有新增的球印','bowl','墙面一天前的球印与今天完全重合；粉尘也没有新落下。',{truth:3}),clue('lamp','小屋补绘节点','mirror','灯芯转动，桌边写字人的衣角重复同一道动作。灯歇，他便淡去。',{truth:3})]},witnessLines:{A:['坊正手里的包袱只装着药和两件童衣。','坊正：小的走得慢。我等他们过了水道就回来。','巡捕检查包袱，没有绳铐，没有换钱的契纸。'],B:['水道出口有擦过石壁的旧衣线头。','有人把短梯留给了后来的人，最低一级沾着新泥。','幻术师把灯挪开。墙后露出一小片没有铺石的荒地。']},puzzle:{A:{text:'户籍四十七人，生活痕迹十九人。对失踪案应先验证哪项？',options:['真实使用痕迹与撤离足迹','户籍人数一定正确','温饭能证明刚才有人'],answer:0},B:{text:'出口的新泥、向外足迹、留给后来人的短梯，指向哪种行动？',options:['分批撤离，非押送贩卖','居民凭空蒸发','全坊从未存在'],answer:0}},verdict:['坊正借更鼓经水道撤离十九名真实居民','坊正拐走了四十七人','暂不定性，保留两组人数'],resolution:['巡捕在四十七个名字旁另列一栏：十九份可核实的生活痕迹。','城墙裂口亮了八息。那边没有灯市，只有荒草和烧黑的砖。','砖色被朱红重新盖住。留下的短梯没有消失。'],after:{TRUTH:6,CHAOS:12}};
C.chapters.granary={title:'战争旧痕之一 · 太仓白灰案',site:'dock',scene:'dock',A:'空粮仓与白灰',B:'地下称重房',witness:'books',meet:'dock',intro:['账册说粮满三仓。打开仓门，回应的却是空响。','仓吏倒在白灰中，四周没有脚印。','一袋写着满重的粮袋，被巡捕轻轻提了起来。'],clues:{A:[clue('grain','虚报粮册','paper','账面粮重与车辙深浅对不上。仓吏在副使签名旁画了圈。',{score:2}),clue('ash','衣领白灰','bowl','灰嵌在衣领内侧，口鼻附近更密；上层地面只是后来落上的浮粉。',{score:2}),clue('scratches','墙上五道一组的划痕','brick','划痕高度不一，旁边分写年龄、身体状况和可负粮重。',{truth:5,requires:{stats:{TRUTH:35,EVIDENCE:7}},flag:'granaryWar',anchor:'grainTag'})],B:[clue('weight','称重升降板','gear','配重可将下层的人送回上层，倾倒槽落粉时不会留下脚印。',{score:2}),clue('bags','小粮袋与旧鞋','cloth','袋子只有成人规格的一半，旁边是磨穿底的小鞋，没有商队名册。',{truth:4,score:2}),clue('conveyor','旧运输机关','gear','传送带空着。斜光里却掠过一列背负粮袋的矮小影子，只留下木轮与脚步声。',{truth:8,requires:{stats:{TRUTH:45},flags:{oldMark:'已见东市旧工匠标记'}},flag:'granaryMemory'})]},witnessLines:{A:['太仓副使：新粮明日入库。眼下只是倒仓。','巡捕把同一辆车两次过磅的数字叠在一起，纸薄处透出完全相同的笔画。','仓吏准备上报的副本，缺了最后一页。'],B:['称重板降到底，侧壁露出另一条更旧的轨道。','轨道不是运一袋粮的宽度。两边扶痕连成很长的一线。','幻术师伸手去推皇库的小门，戒面轻触凹槽，门开了。']},puzzle:{A:{text:'上层没有脚印，衣领有深嵌的白灰。死亡位置应在哪里？',options:['下层称重房，再由升降板送回','上层原地倒下','粮车外'],answer:0},B:{text:'哪组机关能同时解释移尸和无脚印？',options:['称重板下降 → 倾灰 → 配重送回','只开启仓窗','在上层拖行'],answer:0}},verdict:['太仓副使借称重房白灰窒息灭口，升降移尸','仓吏被运粮车撞死','证据不足，暂缓定案'],resolution:['虚报粮册与称重机关的方向对上了。仓门重新封起。','地下墙上的划痕没有抹去。巡捕把一只小粮袋放回旧鞋旁。','两人离开时，谁也没有去数那一长排名字空白的木牌。'],after:{TRUTH:5,CHAOS:5}};
C.chapters.arsenal={title:'战争旧痕之二 · 万骑无声案',site:'market',scene:'dock',A:'马栏与蹄痕',B:'军械坊传声管',witness:'bell',meet:'market',intro:['三夜惊马。第四夜，老马监死在马栏外。','泥地像被整队骑兵踏过，马栏的锁却一个也没有开。','巡捕蹲下量最深的一枚蹄印。幻术师把耳朵贴近地板。'],clues:{A:[clue('hoof','等深蹄印','badge','每一道印的深浅几乎相同，转弯也没有受力偏差，不是真马奔跑。',{score:2}),clue('metal','拆卖军械账','paper','军械坊管事私卖铜件。老马监留下了准备举报的账目。',{score:2}),clue('tags','去名军牌','badge','军牌的姓名被凿去，只余同一枚旧印：腰牌、封泥、粮牌上的缺角终于重合。',{truth:7,flag:'arsenalWar',anchor:'militaryTag',requires:{stats:{TRUTH:50,EVIDENCE:7}}})],B:[clue('pipe','传声管道','rope','低鼓声经管道入木板，栏中的马能感觉震动，却看不见声源。',{score:2}),clue('hooves','机械蹄阵','gear','成排木蹄随同一转轴落下，能在空地刻出一整队马的痕迹。',{score:2}),clue('echo','被封住的训练回声','drum','蹄声从整齐变乱，继而木裂、钟鸣、重撞。最后只剩空管的气流。',{truth:8,flag:'arsenalMemory',requires:{stats:{TRUTH:50}}})]},witnessLines:{A:['管事：马惊了，谁拦得住？','巡捕将泥模倒扣在一起，两枚蹄痕连磨损缺口都相同。','墙上留着密密的兵器挂痕，远多于如今驻军的数目。'],B:['幻术师移开新封的木板。气味沿传声管扑来。','管口的刻记与太仓轨道使用同一组符号。','他没有敲鼓，只让木轮缓缓转过一周。']},puzzle:{A:{text:'真实马蹄转弯时内外侧受力不同；这里每枚等深。应保留哪份比对？',options:['同一机械蹄重复压出的泥模','受惊马匹的毛色','草料数量'],answer:0},B:{text:'锁住的马、空地蹄阵和地下鼓声，怎样对应？',options:['管道惊马；机械蹄阵伪造奔跑；管事实施杀害','真马穿过锁栏','只有气味留下蹄印'],answer:0}},verdict:['管事为掩盖倒卖军械杀人，以鼓声与机械蹄伪造踩踏','锁栏里的马自行冲出杀人','证据不足，暂缓定案'],resolution:['马栏安静下来。泥模与倒卖账被一同装入证物箱。','侧光从空墙掠过，刀枪的旧轮廓密密排列。','两人带走的军牌，没有一个完整的名字。'],after:{TRUTH:5,CHAOS:5}};
C.chapters.master={title:'第五案 · 死人授业案',site:'academy',scene:'academy',A:'旧骨与烧毁画像',B:'老师的三个房间',witness:'temple',meet:'academy',intro:['幻术院送来消息：老师死了。','幻术师还记得昨夜灯下的交谈。推开门，椅上却只剩旧骨与褪色衣料。','巡捕把新灯放低。灰尘在骨缝里结成了多年未动的薄壳。'],clues:{A:[clue('bones','旧衣与骨缝','cloth','衣料制式早已废止，骨缝积灰。新近的谋杀无法解释这些时间痕迹。',{score:2,truth:5}),clue('portrait','烧毁画像残片','paper','半张少年脸留在残片上，指间有一枚熟悉的戒指。三片边缘可相互拼合。',{score:2,flag:'burntPortrait'}),clue('outsider','巡捕的旧俸册','paper','俸册领了三年，留下的私人经历却只从三个月前开始。旧刀柄磨损方向与你惯用手相反。',{truth:6,flag:'outsiderRecord'})],B:[clue('rooms','三处固定光区','mirror','老师只在这三个光区出现，没有一次走到窗外。桌上的笔从未换过。',{score:2}),clue('book','从未接住的书','paper','巡捕把书递来。你记得老师递书的动作，却完全记不起那本书的重量。',{score:2,truth:5,anchor:'teachersBook'}),clue('memory','书页里的旧刻录','mirror','背光处是少年守着老师的最后一夜。此后每一次“授课”，光路都回到同样的位置。',{truth:8,flag:'masterMemory',requires:{stats:{TB:65}}})]},witnessLines:{A:['书吏取出被水浸过的皇族档册。没有完整的人名，只有烧裂的画像框。','巡捕在领取记录上落下自己的笔迹。纸下压着一枚旧印。','这张领取记录，后来查档的人也能看见。'],B:['幻术师翻到档案领取页，认出巡捕刚留下的笔迹。','书吏：残片都在那只匣里。小心灰。','匣中缺角的戒面，与自己手上的那枚一致。']},puzzle:{A:{text:'将三枚残片按画面从左到右排列：衣袖、半张脸、持戒的手。拖动下方残片或依次点击。',options:['衣袖','半张脸','持戒的手'],answer:'0,1,2'},B:{text:'画像脸部残缺。用什么独立物证核对身份？',options:['戒面缺角与皇族机扣','衣服颜色','少年身高'],answer:0}},verdict:['没有新凶手：老师早已死去，授课者是受光路约束的记忆幻象','有人昨夜替换了全部尸骨','暂不接受，继续保留疑点'],resolution:['纸上的半张少年脸，与灯下的人并在一起。戒面缺角严丝合缝。','幻术师把书抱在手中。这一次，他知道它的重量。','巡捕没有替他翻下一页。通往宫城地下的路，就压在书页下面。'],after:{TRUTH:6}};
C.chapters.final={title:'最终章 · 长安无凶',site:'temple',scene:'academy',meet:'temple'};
for(const [key,ch]of Object.entries(C.chapters))if(ch.clues)for(const role of ['A','B'])ch.clues[role].forEach((c,i)=>Object.assign(c,{x:[.18,.48,.8][i],y:[.53,.72,.43][i],w:.11,h:.22,score:c.score??1,key:key+':'+c.id,role}));
// Paint-backed hit regions follow the objects in each chapter illustration.
const paint={
 west:{A:[[.56,.53,.30,.20],[.16,.70,.23,.35],null],B:[[.21,.27,.18,.44],[.40,.31,.17,.48],[.95,.62,.09,.19]]},
 palace:{A:[[.57,.53,.16,.24],[.435,.57,.15,.22],[.48,.85,.27,.22]],B:[[.68,.07,.08,.12],[.90,.30,.17,.40],null]},
 ward:{A:[[.23,.43,.25,.44],null,null],B:[[.87,.72,.20,.38],[.416,.588,.07,.10],[.92,.325,.09,.18]]},
 granary:{A:[[.16,.81,.27,.17],[.54,.70,.25,.23],[.37,.43,.07,.20]],B:[[.84,.40,.27,.56],[.835,.775,.18,.22],[.69,.43,.09,.36]]},
 arsenal:{A:[[.79,.575,.20,.22],null,null],B:[[.435,.25,.15,.22],[.32,.56,.44,.37],[.373,.35,.10,.18]]}
};
for(const key of ['west','palace','ward','granary','arsenal','final'])C.chapters[key].scene='chapter-'+key;
for(const [key,roles]of Object.entries(paint))for(const [role,regions]of Object.entries(roles))regions.forEach((p,i)=>{if(p)Object.assign(C.chapters[key].clues[role][i],{x:p[0],y:p[1],w:p[2],h:p[3],painted:true,scene:C.chapters[key].scene});});
// Loose documents sit on reachable foreground surfaces rather than floating midair.
Object.assign(C.chapters.west.clues.A[2],{x:.84,y:.83,w:.10,h:.14});
Object.assign(C.chapters.ward.clues.A[1],{x:.12,y:.72,w:.09,h:.13});
Object.assign(C.chapters.ward.clues.A[2],{x:.22,y:.86,w:.10,h:.13});
Object.assign(C.chapters.arsenal.clues.A[1],{x:.45,y:.89,w:.12,h:.12});
Object.assign(C.chapters.arsenal.clues.A[2],{x:.61,y:.82,w:.05,h:.10});
C.current=s=>C.chapters[s.campaign?.chapter||'qujiang'];
C.anchors=s=>s.campaign.anchors.length;
C.trueLock=s=>{const a=[];for(const [k,min]of Object.entries({TRUTH:85,TA:75,TB:75}))if(s.stats[k]<min)a.push(`${k} ≥ ${min}（当前 ${s.stats[k]}）`);if(s.stats.CHAOS<30||s.stats.CHAOS>70)a.push(`CHAOS 需在 30–70（当前 ${s.stats.CHAOS}）`);if(C.anchors(s)<3)a.push(`记忆锚定物 ≥ 3（当前 ${C.anchors(s)}）`);for(const [k,t]of [['granaryWar','太仓人口痕迹'],['granaryMemory','太仓残影'],['arsenalWar','军牌旧印'],['arsenalMemory','军械坊回声'],['masterMemory','师父完整记忆'],['royalRing','皇族戒指'],['burntPortrait','残破画像']])if(!s.flags[k])a.push('未完成：'+t);return a.join('；');};
C.finalOptions=s=>s.role==='A'?[{id:'stay',text:'停止，给这座长安再留一夜'},{id:'break',text:'摧毁现实阵眼',lock:s.stats.TRUTH<65||s.stats.CHAOS<70||(s.stats.TA>=50&&s.stats.TB>=50)?'需要 TRUTH ≥ 65、CHAOS ≥ 70，且至少一方信任 < 50':''},{id:'leave',text:'独自走向城外',lock:s.stats.TRUTH<80||(s.stats.TA>=40&&s.stats.TB>=40)?'需要 TRUTH ≥ 80，且至少一方信任 < 40':''},{id:'release',text:'松手',lock:C.trueLock(s)}]:[{id:'stay',text:'维持万象，让灯继续亮着'},{id:'block',text:'守住幻象阵眼，阻止破坏'},{id:'erase',text:'抹去那个无法被预测的巡捕',lock:s.stats.TB>25||s.stats.DREAM<60?'需要 TB ≤ 25、DREAM ≥ 60':''},{id:'leave',text:'独自离开这座长安',lock:s.stats.TRUTH<80||(s.stats.TA>=40&&s.stats.TB>=40)?'需要 TRUTH ≥ 80，且至少一方信任 < 40':''},{id:'release',text:'松手',lock:C.trueLock(s)}];
C.events.prologueA=(s,L)=>[L('n','更鼓未响。大理寺廊下，一个年轻巡捕把腰牌系紧。'),L('clerk','东市失了一面宫镜。工匠还没出市门，去把人带回来。'),L('A','伤了谁没有？'),L('clerk','没有。东西倒砸了不少。别把镜子也弄坏。'),L('n','刀柄硌着掌心。他换了一次握法；旧皮缠绕的方向，与自己的惯用手不合。'),L('A','先找人。'),L('n','市声从坊门后涌来。绸架摇晃，一道身影越过了屋檐。')];
C.events.prologueB=(s,L)=>[L('n','幻术院的领用架空了一格。那是老师不许旁人触碰的铜镜。'),L('B','镜背的止齿松过，拿去很容易伤手。'),L('n','案头的纸写着五年前新制。纸旁却有一圈磨了许久的旧铜粉。'),L('B','东市……他往灯多的地方走了。'),L('n','幻术师收起薄镜，沿坊墙赶去。隔着一条街，他先看见两个人影，才听见一个人的脚步。')];
C.events.meeting=(s,L,Cc)=>[L('n','工匠踩过瓦脊。巡捕翻上屋顶时，另一人正从绸架上落下。'),L('A','让开。大理寺拿人。'),L('B','你追的是左边，右边那个没有脚步声。'),L('n','一块瓦穿过右侧的人影，纸人贴着牵线翻了半圈。'),L('A','你和他一路？'),L('B','我来拿镜子。你来拿人，暂时不冲突。'),L('n','工匠回头，看见铜镜反光，猛地向檐下冲去。'),L('A','下面还有人。','idle',[Cc('撞翻空绸架，封住下街的路',{stats:{CHAOS:3},flags:{clothDropped:true}}),Cc('留住摊位，从屋脊截住他',{stats:{TA:3},flags:{clothDropped:false}})]),L('B','我从另一侧过去。','action',[Cc('借落下的绸布荡向屋顶',{stats:{TA:5,TB:3},flags:{mirrorApproach:'cloth'}},'',{flags:{clothDropped:'巡捕已放倒空绸架'}}),Cc('用铜镜在前方造一条假路',{stats:{TA:5},flags:{mirrorApproach:'mirror'}},'',{values:{clothDropped:[false,'巡捕保留了绸架直路']}}),Cc('沿屋脊继续追击',{stats:{TB:3},flags:{mirrorApproach:'roof'}})]),L('n','两道脚步在檐角会合。工匠举起短刀，另一只手却把铜镜砸向瓦面。')];
C.events.mirrorChoice=(s,L,Cc)=>[L('A','镜子别碎在街上。','action',[Cc('侧身闪避，空出正面',{flags:{combat:'dodge'}}),Cc('迎面格挡，稳住他的手',{stats:{TB:3},flags:{combat:'guard'}}),Cc('扑向将落地的铜镜',{flags:{combat:'mirror'}})]),L('B','我接你留下的位置。','action',[Cc('正面截击',{stats:{TA:5},flags:{combatB:'front'}},'',{values:{combat:['dodge','巡捕选择侧身闪避']}}),Cc('架势防守，护住侧翼',{stats:{TB:5},flags:{combatB:'defend'}},'',{values:{combat:['dodge','巡捕选择侧身闪避']}}),Cc('绕到工匠背后',{stats:{TA:5},flags:{combatB:'back'}},'',{values:{combat:['guard','巡捕选择迎面格挡']}}),Cc('借巡捕遮挡施术',{stats:{TB:5},flags:{combatB:'cover'}},'',{stats:{TB:40},values:{combat:['guard','巡捕选择迎面格挡']}}),Cc('造出第二道巡捕的影子',{stats:{TA:5},flags:{combatB:'double'}},'',{values:{combat:['mirror','巡捕选择保护铜镜']}}),Cc('独自拖住工匠',{stats:{TB:-3},flags:{combatB:'hold'}},'',{values:{combat:['mirror','巡捕选择保护铜镜']}})]),L('n','纸影被风掀起，真正握刀的手只剩一只。')];
C.events.mirrorAfter=(s,L)=>[L('n',s.flags.mirrorSuccess?'巡捕扣住工匠的手，幻术师接稳铜镜。':'短刀划破绸布。工匠跌进空篷，被赶来的坊卒按住；铜镜边缘崩下一小片。'),L('n','工匠不看两人，只盯着那面镜，手指仍朝碎瓦伸。'),L('A','人交给坊卒。东西留下。'),L('B','他的工具袋，你看得懂。我查镜背。'),L('A','查完回来对。别替我把不明白的东西扔掉。')];
C.events.cIntro=(s,L)=>C.current(s).intro.map(t=>L('n',t));
C.events.cWitnessA=(s,L)=>C.current(s).witnessLines.A.map(t=>L('n',t));
C.events.cWitnessB=(s,L)=>C.current(s).witnessLines.B.map(t=>L('n',t));
C.events.cJoint=(s,L,Cc)=>{
 const k=s.campaign.chapter;
 if(k==='west')return [L('B','镜在纱幕后。先动哪一处？','examine',[Cc('揭开主镜',{stats:{TA:5},flags:{stagePlan:'mirror'}}),Cc('熄灭舞台灯',{stats:{CHAOS:3},flags:{stagePlan:'dark'}})]),L('A','我在台口。','idle',[Cc('扑向酒楼主人',{stats:{TB:3}},'',{values:{stagePlan:['mirror','幻术师揭开主镜']}}),Cc('保护侧席证人',{stats:{TB:5}},'',{values:{stagePlan:['mirror','幻术师揭开主镜']}}),Cc('追踪黑暗中的脚步',{stats:{TA:3}},'',{values:{stagePlan:['dark','幻术师熄灭舞台灯']}}),Cc('守住唯一出口',{stats:{TB:5}},'',{values:{stagePlan:['dark','幻术师熄灭舞台灯']}})]),L('n','同一段舞，终于可以从两侧重看。')];
 if(k==='ward')return [L('A','人找到了。先处理眼前的事。','idle',[Cc('听完坊正的解释',{stats:{TB:5,TA:3},flags:{wardMercy:true}}),Cc('先逮捕，封住水道',{stats:{TB:-8},flags:{wardMercy:false}})]),L('B','墙后的光越来越薄。','idle',[Cc('暂留小屋节点，让人走完这段路',{stats:{DREAM:5,TA:3}}),Cc('关闭地下裂口',{stats:{CHAOS:-3,DREAM:3}}),Cc('扩大裂口，照向城外',{stats:{TRUTH:5,CHAOS:10,DREAM:-8}})]),L('n','巡捕把包袱放回短梯边。水道外的风，比坊里冷。')];
 if(k==='master')return [L('A','匣里有张残像。','idle',[Cc('立刻把画像交给幻术师',{stats:{TB:8},flags:{portraitShared:true}}),Cc('暂时隐瞒，独自核对',{flags:{portraitShared:false}})]),L('n',s.flags.portraitShared?'残片被放到两人之间。':'领取页上的笔迹，使后来的查档者知道：巡捕已经看过。'),L('B',s.flags.portraitShared?'原来你也看见了。':'这页字，是你写的。','idle',[Cc('说出最近反复出现的梦',{stats:{TA:8},flags:{dreamShared:true}},'',{flags:{portraitShared:'巡捕已主动交出画像'}}),Cc('先核对戒指，再作判断',{stats:s.flags.portraitShared?{TA:3}:{TA:3,TB:-15},flags:s.flags.portraitShared?{}:{knowsLie:true}}),Cc('质问他为什么隐瞒',{stats:{TB:-15,TA:-8},flags:{knowsLie:true}},'',{values:{portraitShared:[false,'巡捕此前选择隐瞒']}}),Cc('假装不知道，自己记下',{stats:{TB:-15},flags:{knowsLie:true}},'',{values:{portraitShared:[false,'巡捕此前选择隐瞒']}})]),L('A','我在这里。','idle',[Cc('不再追问，坐在他身旁',{stats:{TB:5}},'',{stats:{TA:70}}),Cc('要求先交出幻术工具',{stats:{TB:-8}}),Cc('把核对的时间留给他',{stats:{TB:3}})])];
 return [L('A','把你看到的，和我这份放在一起。','idle',[Cc('先听搭档的记录',{stats:{TB:5,TA:3},flags:{['listen:'+k]:true}}),Cc('只按自己核实的部分推进',{stats:{TB:-8},flags:{['listen:'+k]:false}})]),L('B','还有一处，我没有写进公文。','idle',[Cc('交出异常记录，共同复核',{stats:{TA:5,TRUTH:3},flags:{['share:'+k]:true}},'',{stats:{TB:55}}),Cc('暂留记录，只谈当前案件',{stats:{TA:-3,DREAM:3},flags:{['share:'+k]:false}})]),L('n','两份记录摊开。纸面上不能互相解释的地方，被留成空白。')];
};
C.events.cResolution=(s,L)=>[L('n',s.campaign.lastVerdict===0?'两人的判断得到现场记录支撑。':s.campaign.lastVerdict===1?'这次指认有无法解释的缺口。案卷标为待复核，未将猜测当成定论。':'两人暂缓定案，把未核实的部分保留。'),...C.current(s).resolution.map(t=>L('n',t))];
C.events.qujiangReflection=(s,L,Cc)=>[L('n','案卷合起后，幻术师再次蹲到舷边。他想确认落水时看见的那一点缺口。'),L('n',s.stats.TRUTH>=25?'水上的塔亮着灯。水下的倒影，却少了一座。':'水上的塔亮着灯。水下有一角屋檐，颜色比岸上深。'),L('n','他抬头，塔还在。再低头，倒影也完整了。'),L('A','看见什么了？'),L('B','……','idle',[Cc('没什么',{stats:{DREAM:3}}),Cc('我刚才好像看错了',{stats:{TA:3,TRUTH:3}})]),L('n',s.stats.TRUTH>=40?'风吹过水面。宫城的倒影短暂熄了灯，不到一息，又亮起来。':'风吹散涟漪。刚才不对的地方，已经找不到了。'),L('n','西市的胡鼓声越过坊墙。这一夜的记录，被带到了下一案。')];
C.events.finalDescent=(s,L,Cc)=>[L('n','地道尽头没有新的报案。石阶仍往下。'),L('n','曲江的水道从脚下穿过；纱幕后的铜镜在墙中延伸；凹镜、运输轨道、传声管，在这里汇成一套结构。'),L('A','这些接口，前面都见过。'),L('B','门上的缺口，和戒面一样。','examine',[Cc('取下戒指，嵌入旧机扣',{flags:{finalGateOpen:true}})]),L('n','戒面嵌入门上的缺口。机扣退开，光第一次没有补上门后的焦痕。'),L('n','门外仿佛仍是朱雀街。一步之后，灯笼变成焦梁。再一步，舞影退去，留下原来站立的位置。'),L('n','旧刻录的落款停在十二年前，最后一道诏印署着东宫。少年守在老师身旁，远处宫墙倾倒。他没有离开，而是把一面面镜转向空城。'),L('n','最后一格刻录里，少年亲手遮住写着自己姓名的一页。此后的光影里，只剩“御用幻术师弟子”。'),L('B','是我把那一页遮住的。'),L('n','另一面墙上，一道城外足迹停在三个月前。空着的巡捕名册，把来人的影子补了进去。'),L('A','腰牌是真的。可我不是原来拿它的人。'),L('B','这一路，你也不是照着名册走的。'),L('n','石门从两人之间合拢。现实阵眼与幻象阵眼，各亮起一面不同的铭片。')];
C.qte=(s)=>s.role==='A'?[['踏稳檐角','W','踏稳'],['扣住持刀手腕','A','扣腕'],['收住落下的铜镜','D','接镜']]:[['拉紧绸布牵线','D','牵线'],['辨清纸人真身','A','辨影'],['托住镜背止齿','W','托镜']];
C.endings={night:{title:'长安不夜',A:'更鼓后，大理寺的案头多了一封新报案。你系好腰牌，记得有个人会在坊门口等你。',B:'画舫重新开宴，诗人举杯。你收起镜子，沿着灯火走向坊门。你没有再数水中的塔。',tail:'城外的荒草，没有被这一夜的灯照到。'},broken:{title:'破梦',A:'朱雀镜裂开，新的身份随光退去。你恢复城外的记忆，却在那三个月的位置留下了一块空白。',B:'所有未被准备好接住的记忆一齐涌回。宫墙不再恢复。你坐在残镜前，认不出自己的手。',tail:'这一回，更鼓没有把碎片收拢。'},dreamer:{title:'梦中人',A:'腰牌上的名字先模糊，随后是一路记下的案卷。你伸手去抓，指间只余空纸。',B:'第二天，大理寺来了一个新巡捕。东市又有工匠抱着铜镜逃走。你觉得这一幕很熟悉。',tail:'第一章。'},alone:{title:'独醒',A:'你们终于走到了同一道门前，却没有选择同一侧。',B:'你们终于走到了同一道门前，却没有选择同一侧。',tail:'两人的最后一幅长安，从此不同。'},true:{title:'未·央',A:'城外的记忆渐渐回来。那三个月却没有消失：你记得杯底的灰、湿绳的重量，也记得另一个人伸来的手。',B:'你没有再把废墟铺成宫城。只在一张桌上，留下小小的朱雀街、曲江与灯火。',tail:'幻术师：“假的？”\n巡捕：“假的。”\n停了片刻。\n“但挺好看。”'}};
root.CAMPAIGN=C;if(typeof module!=='undefined')module.exports=C;
})(typeof window!=='undefined'?window:globalThis);
