(function(root){
const P=root.CAMPAIGN;
const esc=t=>String(t).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const names={TA:'巡捕对幻术师的信任',TB:'幻术师对巡捕的信任',TRUTH:'真相认知',DREAM:'幻境依恋',CHAOS:'幻境失稳',EVIDENCE:'证据完整度'};
const words=t=>esc(t).replace(/\b(TA|TB|TRUTH|DREAM|CHAOS|EVIDENCE)\b/g,k=>names[k]);
// Evidence previews are crops of the same illustration used during investigation.
const object=c=>`<div class="painted-preview" style="--crop-ratio:${c.w*1672/(c.h*941)};background-image:url('assets/scenes/${c.scene}.png');background-size:${100/c.w}% ${100/c.h}%;background-position:${(c.x-c.w/2)/(1-c.w)*100}% ${(c.y-c.h/2)/(1-c.h)*100}%"></div>`;
const backdrop=(scene,extra='')=>`<div class="backdrop ${extra}" style="background-image:url('assets/scenes/${scene}.png')"></div><div class="vignette"></div>`;
const actor=(r,pose='')=>`<img class="chapter-portrait ${r==='A'?'left':'right'}" src="assets/cutouts-complete/${r.toLowerCase()}${pose}.png" alt="${r==='A'?'巡捕':'幻术师'}">`;
function notebook(s){const c=s.campaign,ch=P.current(s);return `<div class="eyebrow">${ch.title}</div><p class="help">${c.sharedNotes?'两份记录已在会合时交换。':'仅显示你独立取得的记录；会合后可核对搭档的发现。'}</p><div class="notebook-grid">${['A','B'].flatMap(r=>(r===s.role||c.sharedNotes?ch.clues?.[r]||[]:[]).filter(x=>c.found[r].includes(x.id)).map(x=>`<article class="evidence-entry"><div class="campaign-object-preview">${object(x)}</div><h3>${x.name}</h3><p>${x.text}</p><small>${r==='A'?'巡捕':'幻术师'}的记录</small></article>`)).join('')||'<p class="help">尚无本案记录。</p>'}</div><h3>记忆锚定物</h3><p class="help">${c.anchors.map(x=>({brick:'烧焦宫砖',grainTag:'无名粮牌',militaryTag:'去名军牌',teachersBook:'师父旧书'}[x])).join(' · ')||'尚未取得'}</p><h3>已完成案件</h3><p class="help">${c.results.map(x=>P.chapters[x.chapter].title+' · '+['完整复原','待复核','保留疑点'][x.verdict]).join('<br>')||'本案进行中'}</p>`;}
function page(s,g){const c=s.campaign,ch=P.current(s),role=s.role;
 if(s.view==='chapterInvestigate'){const clues=ch.clues[role],selected=clues.find(x=>x.id===s.insight?.chapterClue);return `<div id="panorama" class="panorama campaign-panorama"><div class="pano-track"><img class="pano-image" src="assets/scenes/${ch.scene}.png" alt="${ch[role]}，拖动环视" draggable="false"><div class="chapter-scene-shade"></div>${clues.map(x=>`<button class="object-hit" data-campaign-object="${x.id}" aria-label="查看此处" style="left:${(x.x-x.w/2)*100}%;top:${(x.y-x.h/2)*100}%;width:${x.w*100}%;height:${x.h*100}%"></button>`).join('')}${s.flags.granaryMemory&&c.chapter==='granary'?'<div class="grain-procession" aria-hidden="true">'+Array.from({length:13},()=>'<i></i>').join('')+'</div>':''}</div></div><button class="scene-visibility quiet" data-action="toggleSceneUI">净览画面 · H</button><div class="invest-head"><p>${ch.title} · ${ch[role]}</p><small>拖动环视，点击物件。已记录 ${c.found[role].length} / ${clues.length}</small></div>${selected?`<aside class="insight"><div class="campaign-object-preview">${object(selected)}</div><div class="eyebrow">新记入案卷</div><p>${selected.text}</p>${c.chapter==='arsenal'&&selected.id==='echo'?'<button class="btn" data-action="replayEcho">转动旧鼓 · 重听回声</button>':''}<button class="quiet" data-action="dismissInsight">收起记录</button></aside>`:''}<div class="invest-bottom"><div class="compass-control"><button data-action="panLeft">‹</button><input id="panRange" aria-label="环视位置" type="range" min="0" max="1000" value="0"><button data-action="panRight">›</button></div><button class="btn" data-action="chapterMap">返回地图 · 继续问询</button><button class="btn primary" data-action="chapterMeet">会合验证</button></div>`;}
 if(s.view==='chapterPuzzle'){const p=ch.puzzle[role],experiment=c.chapter==='palace',step=c.experiment?.[role]||0,portrait=c.chapter==='master'&&role==='A';return `${backdrop(ch.scene)}<section class="panel-screen campaign-panel"><div class="eyebrow">${ch.title} · 双人验证</div><h1>${portrait?'把残像拼回去':'让两份记录相互验证'}</h1><p class="help">${p.text}</p><p class="help">另一位玩家持有不同的信息，请互相说明自己的观察。</p>${experiment?`<div class="reset-experiment step-${step}"><div class="vase-fragment"></div><div class="vase-body"></div><div class="vase-mark">丶</div><p>${['花瓶在桌上，窗台空着。','碎片移到窗台。内壁留下你的一笔。','更鼓响过，瓶身完整，窗台空了。','提灯看向内壁：记号仍在。'][step]}</p></div>${step<3?`<button class="btn primary" data-action="chapterExperiment">${['移动碎片 · 留下记号','等待更鼓 · 看它复原','提灯 · 复查内壁'][step]}</button>`:''}`:''}${portrait?`<div class="portrait-fragments" id="fragments">${[2,0,1].map(i=>`<button draggable="true" data-fragment="${i}" class="portrait-fragment frag-${i}" aria-label="${p.options[i]}"><span>${p.options[i]}</span></button>`).join('')}</div><p class="help" id="fragment-order">从左到右排列。也可依次点击三片。</p><button class="btn primary" data-action="fragmentSubmit">核对残像</button>`:`<div class="choice-row">${p.options.map((t,i)=>`<button class="choice" data-action="chapterPuzzle" data-answer="${i}" ${experiment&&step<3?'disabled':''}>${t}</button>`).join('')}</div>`}<p class="help">${s.notice||''}</p><button class="quiet" data-action="notebook">核对我的案卷</button></section>`;}
 if(s.view==='chapterVerdict')return `${backdrop(ch.scene)}<section class="panel-screen campaign-panel"><div class="eyebrow">${ch.title} · 共同落笔</div><h1>这一案，如何写入案卷</h1><p class="help">双方分别提交，判断一致才结案。证据完整度：${s.stats.EVIDENCE} / 10</p><div class="choice-row">${ch.verdict.map((t,i)=>`<button class="choice" data-action="chapterVerdict" data-answer="${i}" ${i===0&&s.stats.EVIDENCE<6?'disabled':''}>${t}${i===0&&s.stats.EVIDENCE<6?`<small class="lock-reason">需要证据完整度 ≥ 6，当前 ${s.stats.EVIDENCE}</small>`:''}</button>`).join('')}</div><p class="help">${s.notice||''}</p><button class="quiet" data-action="notebook">回看共同案卷</button></section>`;
 if(s.view==='chapterDrum'){const next=P.chapters[P.order[P.order.indexOf(c.chapter)+1]];return `${backdrop('bell')}<section class="waiting-card chapter-drum"><div class="eyebrow">更鼓 · 共同记忆</div><h1>把这一夜留下</h1><p>两人确认后，自动存档并进入「${next.title}」。</p><p class="help">${s.stats.TRUTH>=30&&!c.anchors.length?'尚无锚定物：更鼓将使真相认知 −1。':c.anchors.length?'锚定物守住了这一夜的记忆。':'更鼓声越过坊墙。'}${s.stats.CHAOS>=80?'<br>幻境失稳已达 80：街巷将封锁，万象台提前开启。':''}</p><button class="btn primary" data-action="drumConfirm" ${c.drum[role]?'disabled':''}>${c.drum[role]?'已确认 · 等待搭档':'确认今夜发生的一切'}</button><button class="quiet" data-action="checkpoints">共同存档</button></section>`;}
 if(s.view==='finalChoice')return `${backdrop('chapter-final','final-backdrop')}${actor(role)}<section class="panel-screen final-panel"><div class="eyebrow">长安无凶 · ${role==='A'?'现实阵眼':'幻象阵眼'}</div><h1>${role==='A'?'铭片的这一面':'铭片的另一面'}</h1><p class="private-message">${role==='A'?'关闭城市覆盖，城外幸存者将逐渐恢复记忆。你的旧人生也会回来；铭片却没有说，巡捕的三个月是否会留下。':'关闭城市覆盖，大量依靠幻境维持心理稳定的人会面对全部旧记忆。缓慢停机能保留一枚小型核心，但需要另一端同时放开控制。'}</p><p class="help">这是你这一侧看到的信息。先与搭档交流，再决定。${s.flags.knowsLie?'画像的那次隐瞒，仍留在两人之间。':''}</p><div class="choice-row">${P.finalOptions(s).map(o=>`<button class="choice" data-action="finalSubmit" data-id="${o.id}" ${o.lock?'disabled':''}>${o.text}${o.lock?`<small class="lock-reason">${words(o.lock)}</small>`:''}</button>`).join('')}</div><p class="help">${s.notice||''}</p></section>`;
 if(s.view==='campaignEnd'){const end=P.endings[c.ending],left=c.departures?.[role];return `${backdrop(c.ending==='night'||c.ending==='dreamer'||(c.ending==='alone'&&!left)?'lake':'temple',c.ending==='true'||(c.ending==='alone'&&left)?'ruin-layer':'')}<section class="outro campaign-ending"><div class="eyebrow">终章 · 两人共同走过的长安</div><h1>${end.title}</h1><p>${end[role]}</p>${c.ending==='alone'?`<p>${left?'你跨过城门。残墙与荒草真实地留在风里，身后的灯火不再覆盖它们。':'你留在城门内。灯亮了起来，另一人的位置却一直空着。'}</p>`:''}${c.ending==='true'?'<div class="mini-changan" aria-label="桌面上亮起一座微型长安"><img src="assets/map-ground.png" alt="桌面微型长安"></div>':''}<p>${end.tail.replaceAll('\n','<br>')}</p><p class="help">完成 ${c.results.length} 起案件 · 记忆锚定物 ${c.anchors.length} 件<br>这段经历已经保存在共同存档中。</p><div class="choice-row"><button class="btn" data-action="checkpoints">回到共同存档 · 重走分支</button><button class="btn" data-action="notebook">翻阅案卷</button><button class="quiet" data-action="newGame">返回开始</button></div></section>`;}
 return '';
}
root.CAMPAIGN_UI={page,notebook};
})(window);
