(()=>{
'use strict';
const P=window.CAMPAIGN,U=window.CAMPAIGN_UI,D=window.GAME_DATA,app=document.getElementById('app'),SAVE='changan-demo-online-v3';
let connection=null,events=null,pollTimer=null,pollGeneration=0,transport=null,clockOffset=0,selectedRole=null,busy=false,online=false,hostUrls=[],game=new Game(),modal=null,pan=0,panScene='',sceneUIHidden=false,drag=null,toastTimer=null,frame=0,qteRemaining=0,qteStamp=0,qteLock=false,stepToken='',flash='',lastFocus=null;
const s=()=>game.s;
const sceneImage=id=>'assets/scenes/'+id+'.png';
const poseImage=(who,pose='idle')=>{
 if(who==='A'||who==='B')return pose==='idle'?'assets/cutouts-complete/'+who.toLowerCase()+'.png':'assets/cutouts-complete/'+who.toLowerCase()+'-'+pose+'.png';
 const variants={host:'defend',boatwoman:'point',poet:'write'};
 return variants[who]&&pose!=='idle'?'assets/cutouts-complete/'+who+'-'+variants[who]+'.png':'assets/cutouts-complete/'+who+'.png';
};
const roleName=r=>D.roles[r].name;
const statNames={TA:'巡捕对幻术师的信任',TB:'幻术师对巡捕的信任',TRUTH:'真相认知',DREAM:'幻境依恋',CHAOS:'幻境失稳',EVIDENCE:'证据完整度'};
const readable=text=>String(text).replace(/\b(TA|TB|TRUTH|DREAM|CHAOS|EVIDENCE)\b/g,k=>statNames[k]);
const fmt=d=>Object.entries(d||{}).filter(([,v])=>v).map(([k,v])=>statNames[k]+' '+(v>0?'+':'')+v).join(' · ');
function readSave(){try{return JSON.parse(sessionStorage.getItem(SAVE))}catch{return null}}
function save(){}
function accept(state){if(s().net?.revision===state.net.revision&&s().net?.peerOnline===state.net.peerOnline)return;const old=s().net,restored=old&&old.timeline!==state.net.timeline,newSave=old&&(state.net.checkpoints?.length||0)>(old.checkpoints?.length||0);const before=old&&!restored?{...s().stats}:null;if(restored){modal=null;panScene='';stepToken='';qteLock=false;flash='';}if(state.net.loadRequest)modal='checkpoints';game=new Game(state);online=true;clockOffset=state.net.serverNow?state.net.serverNow-Date.now():0;if(!drag){render();const changed=before&&effectToast(before);if(restored)toast('双方已回到共同存档点，可以重新选择。');else if(newSave&&!changed)toast('共同存档已自动保存 · '+state.net.checkpoints.at(-1).label);}}
async function request(path,body){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',...(connection?{Authorization:'Bearer '+connection.token}:{})},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'连接失败');return data;}
async function connect(data){connection={room:data.room,token:data.token};sessionStorage.setItem(SAVE,JSON.stringify(connection));if(data.state)accept(data.state);events?.close();clearTimeout(pollTimer);const generation=++pollGeneration;
 if(!transport){try{const host=await fetch('/api/host').then(r=>r.json());hostUrls=host.urls||[];transport=host.transport||'sse';}catch{toast('无法连接房间服务，请稍后重试。');return;}}
 if(transport==='poll'){
  async function poll(){if(generation!==pollGeneration||!connection)return;try{const res=await fetch('/api/state?room='+encodeURIComponent(connection.room),{headers:{Authorization:'Bearer '+connection.token}});const payload=await res.json();if(generation!==pollGeneration)return;if(!res.ok){if([401,404].includes(res.status)){toast(payload.error);return;}throw Error(payload.error);}if(payload.state.net.revision>=(s().net?.revision||0))accept(payload.state);}catch(e){if(online)toast('连接暂时中断，正在重连；进度会保留。');online=false;}if(generation===pollGeneration)pollTimer=setTimeout(poll,document.hidden?5000:1500);}poll();
 }else{events=new EventSource('/api/events?room='+encodeURIComponent(connection.room)+'&token='+encodeURIComponent(connection.token));events.onmessage=e=>{const state=JSON.parse(e.data);if(state.net.revision>=(s().net?.revision||0))accept(state);};events.onerror=()=>{online=false;toast('连接暂时中断，正在重连；身份和进度会保留。');};}}
async function send(action){if(!connection||busy)return;const choiceStats=action.type==='next'&&game.currentLine()?.choices&&game.currentLine().who===s().role?{...s().stats}:null;busy=true;try{const data=await request('/api/action',{room:connection.room,action:{...action,timeline:s().net?.timeline},requestId:crypto.randomUUID()});if(data.state.net.revision>=(s().net?.revision||0))accept(data.state);if(choiceStats&&Object.keys(choiceStats).every(k=>choiceStats[k]===data.state.stats[k]))toast('数值变化 · 本次选择数值不变');}catch(e){toast(e.message)}finally{busy=false}}
async function enterRoom(join){if(location.protocol==='file:'){toast('请先双击“启动联机.command”，从联机地址打开游戏。');return;}try{const room=document.getElementById('roomCode')?.value.trim().toUpperCase();const data=await request(join?'/api/join':'/api/rooms',{role:selectedRole,room});connect(data);}catch(e){toast(e.message)}}
function lobbyMarkup(){const invitation=((['localhost','127.0.0.1'].includes(location.hostname)?hostUrls[0]:null)||location.origin)+'/?room='+connection.room;return `<section class="network-panel"><div class="eyebrow">两位真人 · 各守一条线索</div><h1>等待另一位入局</h1><p>你已锁定为${roleName(s().role)}。将地址与房间码交给搭档，搭档选择另一位角色加入。</p><div class="room-code">${connection.room}</div><input class="invite-link" aria-label="邀请地址" readonly value="${invitation}"><button class="btn" data-action="copyInvite">复制邀请</button><p class="help">搭档打开上方邀请链接，选择另一个身份并加入即可。无需下载游戏或注册账户。</p></section>`;}
function renderLobby(){shell(`${bg('lake')}${lobbyMarkup()}`)}
function renderWaiting(){shell(`${bg(s().scene)}${character(s().role,'examine',s().role==='A'?'left':'right',true)}<section class="waiting-card"><div class="eyebrow">${roleName(s().role)} · 房间 ${s().net.room}</div><h1>留一盏灯，等另一人</h1><p>你已完成这一步。搭档完成自己的阅读、调查或动作后，两人一起继续。</p><div class="waiting-pulse"></div><button class="btn" data-action="notebook">查看我的案卷</button></section>`)}
function toast(text){text=readable(text);document.querySelector('.toast')?.remove();clearTimeout(toastTimer);const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);toastTimer=setTimeout(()=>el.remove(),text.startsWith('数值变化')?5000:3500)}
function effectToast(before){const d={};for(const k in s().stats){let n=s().stats[k]-before[k];if(n)d[k]=n;}if(Object.keys(d).length){toast('数值变化 · '+fmt(d));return true;}return false;}
function particles(){return '<div class="particles">'+Array.from({length:15},(_,i)=>`<i style="left:${(i*23+5)%100}%;top:${(i*17+25)%95}%;animation-delay:${i*.6}s"></i>`).join('')+'</div>'}
function bg(id,cls=''){return `<div class="backdrop ${cls}" style="background-image:url('${sceneImage(id)}')"></div><div class="vignette"></div>${particles()}`}
function header(){return `<header class="topbar"><div class="brand">未·央<small>双人叙事解谜 · 完整篇</small></div>${s().view!=='start'?`<span class="role-tag">${roleName(s().role)} · 身份固定 ${s().net?' · '+s().net.room+' · '+(s().net.peerOnline?'搭档在线':'等待搭档连接'):''}</span>`:''}<nav class="nav">${s().view!=='start'?'<button data-action="notebook">案卷</button><button data-action="progress">双人进度</button><button data-action="checkpoints">存档</button>':''}<button data-action="settings">设置</button><button data-action="help">玩法</button></nav></header>`}
function shell(body,cls=''){app.innerHTML=`<main class="${cls}${s().view==='chapterInvestigate'&&sceneUIHidden?' scene-unobstructed':''}">${body}${header()}<div class="grain"></div></main>${modal?modalHTML():''}`;initPanorama();const sceneToggle=app.querySelector('.scene-visibility');if(sceneToggle)sceneToggle.textContent=sceneUIHidden?'恢复界面 · H':'净览画面 · H';if(s().view==='qte'&&!s().waiting)startClock();if(modal){const focusable=app.querySelector('.modal button');focusable?.focus();}save();}
function render(){cancelAnimationFrame(frame);if(['chapterInvestigate','chapterPuzzle','chapterVerdict','chapterDrum','finalChoice','campaignEnd'].includes(s().view)&&!s().waiting){if(s().view==='chapterInvestigate'&&panScene!==s().campaign.chapter+s().role){panScene=s().campaign.chapter+s().role;pan=0;}shell(U.page(s(),game),'campaign-page');initFragments();return;}if(s().waiting&&s().view!=='deduce')return renderWaiting();const views={lobby:renderLobby,start:renderStart,map:renderMap,dialog:renderDialog,investigate:renderInvestigate,match:renderMatch,qteReady:renderQte,qte:renderQte,deduce:renderDeduce,end:renderEnd};(views[s().view]||renderStart)();}
function renderStart(){shell(`${bg('lake')}<div class="start-content"><div class="start-copy"><span class="seal">序 · 入长安</span><div class="eyebrow">今夜，你从谁的眼中看长安</div><h1>未·央</h1><h2>长安九章 · 双影同行</h2><p>从东市追镜，到曲江沉月。<br>循着八起案件留下的痕迹，走进万象长安。<br>你的选择，决定搭档还有哪些路可走。</p>${readSave()?'<button class="btn resume" data-action="resume">重连原房间</button>':''}</div><div class="role-cards">${['A','B'].map(r=>`<button class="role-card ${selectedRole===r?'selected':''}" data-role="${r}" aria-label="选择${roleName(r)}"><img src="assets/cutouts-complete/${r.toLowerCase()}.png" alt="${roleName(r)}"><div class="role-card-copy"><span>${r==='A'?'大理寺':'幻术院'}</span><h3>${roleName(r)}</h3><span>${D.roles[r].subtitle}</span><b>以此身份入长安　↗</b></div></button>`).join('')}</div></div>${selectedRole?`<div class="room-actions"><strong>已选择${roleName(selectedRole)}</strong><button class="btn primary" data-action="createRoom">创建双人房间</button><input id="roomCode" maxlength="8" placeholder="房间码" aria-label="房间码" value="${new URLSearchParams(location.search).get('room')?.replace(/[^A-Z0-9]/gi,'').slice(0,8)||''}"><button class="btn" data-action="joinRoom">加入搭档</button></div>`:''}<div class="start-footer">${location.protocol==='file:'?'请先双击项目中的「启动联机.command」，再从联机地址进入':'双人真人联机 · 身份选定后固定 · 独立调查 · 关键节点双方验证'}</div>`)}
function recommended(){if(s().campaign?.chapter!=='qujiang'){const ch=P.current(s());return s().campaign.found[s().role].length>=2&&!s().campaign.witness[s().role]?ch.witness:ch.site;}if(!s().flags.murder||!s().flags['cabin'+s().role])return 'boat';if(s().role==='A'&&!s().flags.witness)return 'shrine';if(s().role==='B'&&!s().flags.workshop)return 'academy';return game.readyToMeet()?'boat':null;}
function renderMap(){const campaign=s().campaign?.chapter!=='qujiang';const rec=recommended();const flags=s().flags;shell(`<div class="map-stage"><svg class="world-svg" viewBox="0 0 1672 941" aria-label="曲江区域手绘地图" preserveAspectRatio="xMidYMid slice"><image class="map-base" href="assets/map-ground.png" width="1672" height="941"/>${D.locations.map(l=>{const layer=window.MAP_LAYERS?.[l.id];return layer?`<g class="map-region ${rec===l.id?'recommended':''}" role="button" tabindex="0" aria-label="前往${D.scenes[l.id]}" data-location="${l.id}"><image class="map-building-base" href="assets/layers/${l.id}.png" x="${layer.x}" y="${layer.y}" width="${layer.w}" height="${layer.h}"/><g class="map-building-lift" aria-hidden="true"><image class="map-building-copy" href="assets/layers/${l.id}.png" x="${layer.x}" y="${layer.y}" width="${layer.w}" height="${layer.h}"/><path class="map-building-rim" d="${layer.path}"/></g><path class="silhouette-hit" d="${layer.path}"/></g>`:''}).join('')}</svg></div><div class="map-caption">${P.current(s()).title}</div><div class="map-hud"><div class="eyebrow">${roleName(s().role)} · ${P.current(s()).title}</div><p>${game.task()}</p><div class="progress-dots" aria-label="案件进度">${(campaign?P.order.map(k=>s().campaign.results.some(r=>r.chapter===k)):[flags.murder,flags.cabinA,flags.witness,flags.cabinB,flags.workshop,flags.validated,flags.chaseDone]).map(x=>`<i class="${x?'done':''}"></i>`).join('')}</div></div><div class="map-controls"><span class="role-tag">${roleName(s().role)}独立行动</span>${campaign?(s().campaign.stage==='intro'?'<button class="btn primary" data-action="chapterTravel">赶往东市</button>':'<button class="btn" data-action="chapterTravel">进入本案现场</button><button class="btn" data-action="chapterWitness">前往问询</button><button class="btn primary" data-action="chapterMeet">会合验证</button>'):game.readyToMeet()?`<button class="btn primary" data-action="meet">${flags.validated?'返回画舫':'会合 · 验证两份发现'}</button>`:''}</div><div class="save-indicator">联机进度自动保存</div>`)}
function character(who,pose,side,active){if(pose==='examine'&&!['workshop','reunion'].includes(s().event))pose='idle';if(!['A','B','host','poet','boatwoman'].includes(who))return '';return `<img class="character ${side} ${active?'active':'idle'} ${pose==='action'?'action':''} ${who==='B'&&side==='right'&&pose==='idle'?'face-partner':''}" src="${poseImage(who,pose)}" alt="${D.speakers[who]}" draggable="false">`}
function renderDialog(){const l=game.currentLine();if(!l)return;s().scene=game.sceneFor(s().event);const isPartner=['A','B'].includes(l.who),npc=['host','poet','boatwoman'].includes(l.who);let chars='';if(isPartner){chars=character(l.who,l.pose,l.who==='A'?'left':'right',true);if(['feast','reunion','waterEntry','alarm','afterWater','beforeChase','afterChase','meeting','mirrorChoice','mirrorAfter','cJoint','finalDescent'].includes(s().event))chars+=character(l.who==='A'?'B':'A','idle',l.who==='A'?'right':'left',false);}else if(npc){chars=character(l.who,l.pose,'right',true)+character(s().role,'idle','left',false);}
const partnerTurn=l.choices&&['A','B'].includes(l.who)&&l.who!==s().role;
const options=partnerTurn?(s().net?.decision!==undefined?`<div class="partner-decision">搭档选择：${l.choices[s().net.decision].text}</div><button class="choice next" data-choice="0">听到了 · 继续</button>`:`<div class="partner-decision">等待${roleName(l.who)}作出决定……</div>`):l.choices?l.choices.map((c,i)=>`<button class="choice" data-choice="${i}" ${game.choiceLock(c)?'disabled':''}><span class="choice-text">${c.text}</span>${game.choiceLock(c)?`<small class="lock-reason">${readable(game.choiceLock(c))}</small>`:''}${s().debug?`<div class="delta">${fmt(c.effects.stats)||'数值不变'}</div>`:''}</button>`).join(''):'';
shell(`${bg(s().scene)}<div class="scene-mark">${s().campaign?.chapter!=='qujiang'?P.current(s()).title:D.scenes[s().scene]}${s().event.startsWith('intro')&&s().flags.murder?' · 同一夜稍早':''}</div><div class="dialog-world">${chars}</div>${l.choices?`<div class="decision-shade" aria-hidden="true"></div><section class="dialog-choices" aria-label="剧情选择"><div class="choice-row">${options}</div></section>`:''}<section class="dialog-box antique-dialog"><div class="speaker name-plaque">${D.speakers[l.who]||'夜色'}</div><div class="dialog-scroll">${s().event==='reunion'&&s().index===1&&s().stats.TB<55?`<div class="scene-condition">坦诚补述未开启 · 需要 幻术师对巡捕的信任 ≥ 55（当前 ${s().stats.TB}）</div>`:''}<p class="dialog-text ${l.who==='n'?'narration':''}">${l.text}</p></div>${!l.choices?'<button class="dialog-continue" data-choice="0" aria-label="继续对话">续 <span aria-hidden="true">◇</span></button>':''}</section>`,'page-fade dialog-page');}

function sceneClues(){return Object.entries(D.clues).filter(([,c])=>c.scene===s().scene&&c.x!==undefined);}
function preview(id){const c=D.clues[id];if(c.x===undefined)return `<div class="object-preview"><img src="${sceneImage(c.scene)}" alt="" style="width:100%;height:100%;object-fit:cover;left:0;top:0"></div>`;return `<div class="object-preview"><img src="${sceneImage(c.scene)}" alt="物件细节" style="width:${100/c.w}%;height:${100/c.h}%;left:${-(c.x-c.w/2)/c.w*100}%;top:${-(c.y-c.h/2)/c.h*100}%"></div>`;}
function mechanismHTML(mode='inspect'){
 const step=s().qte?.step||0,success=s().qte?.success||0;
 const teeth=Array.from({length:16},(_,i)=>`<rect x="-8" y="-103" width="16" height="22" rx="2" transform="rotate(${i*22.5})"/>`).join('');
 const spokes=Array.from({length:6},(_,i)=>`<path d="M-7 -20 L-12 -78 Q0 -88 12 -78 L7 -20Z" transform="rotate(${i*60})"/>`).join('');
 const wheel=`${teeth}<circle r="85" fill="#614729" stroke="#c39955" stroke-width="11"/><circle r="69" fill="#142324" stroke="#99733e" stroke-width="3"/>${spokes}<circle r="24" fill="#b28a4c" stroke="#d8b26e" stroke-width="4"/><circle r="9" fill="#283335"/>`;
 return `<div class="mechanism-motion ${mode} ${flash||''} ${success>=2?'stabilized':''}" style="--gate-lift:${success*19}px" aria-hidden="true"><svg viewBox="0 0 660 410"><path d="M70 370V90H310V370M40 370H350" fill="none" stroke="#3d3025" stroke-width="22"/><path d="M70 370V90H310V370" fill="none" stroke="#8d6842" stroke-width="3"/><path class="drive-cord" d="M175 215V44H480V138" fill="none" stroke="#bc9a64" stroke-width="7" stroke-dasharray="5 3"/><g transform="translate(175 225)"><g class="drive-wheel" fill="#937043" stroke="#c39a5c" stroke-width="2">${wheel}</g></g><g transform="translate(313 278) scale(.49)"><g class="driven-wheel" fill="#937043" stroke="#c39a5c" stroke-width="2">${wheel}</g></g><circle cx="480" cy="44" r="22" fill="#4b4231" stroke="#bc9a64" stroke-width="6"/><path d="M407 370V137H555V370" fill="#081719" stroke="#76614a" stroke-width="14"/><g class="sluice-gate"><rect x="422" y="150" width="118" height="211" fill="#4c3e2d" stroke="#b79459" stroke-width="5"/>${[185,230,275,320].map(y=>`<path d="M428 ${y}H534" stroke="#947446" stroke-width="9"/>`).join('')}<path d="M436 154V356M526 154V356" stroke="#352e26" stroke-width="8"/></g><path class="water-flow" d="M425 361Q445 338 464 365T507 362T551 370M412 384Q445 357 481 386T565 390" stroke="#9bdae0" stroke-width="5" fill="none"/><g class="mechanism-sparks" fill="#ffe4a5"><circle cx="270" cy="254" r="3"/><circle cx="287" cy="244" r="2"/><circle cx="280" cy="275" r="3"/></g></svg></div>`;
}
function insightHTML(){if(!s().insight)return '';const {id,role}=s().insight,c=D.clues[id];return `<aside class="insight" role="status">${preview(id)}${['gear','rope'].includes(id)?mechanismHTML('inspect'):''}<div class="eyebrow">${roleName(role)}的观察</div><p>${c[role]}</p>${s().debug?`<div class="delta">${c.score?'证据完整度 +'+c.score:''} ${c.truth?'真相认知 +'+c.truth:''}（同一证物只计一次）</div>`:''}<button class="quiet" data-action="dismissInsight">记入案卷 · 继续查看</button></aside>`;}
function renderInvestigate(){if(panScene!==s().scene){panScene=s().scene;pan=s().scene==='cabin'&&s().role==='B'?1:0;}const clues=sceneClues(),n=clues.filter(([id])=>s().observations[s().role].includes(id)).length;shell(`<div id="panorama" class="panorama"><div class="pano-track"><img class="pano-image" src="${sceneImage(s().scene)}" alt="${D.scenes[s().scene]}全景，可拖动环视" draggable="false">${clues.map(([id,c])=>`<button class="object-hit ${s().observations[s().role].includes(id)?'found':''}" data-object="${id}" aria-label="查看此处${s().observations[s().role].includes(id)?'，已记录':''}" style="left:${c.x*100}%;top:${c.y*100}%;width:${c.w*100}%;height:${c.h*100}%"></button>`).join('')}</div></div><div class="invest-head"><p>${roleName(s().role)} · 静看${s().scene==='cabin'?'舱中':'水下'}</p><small>按住画面拖动环视；直接点击可疑物件。</small><span class="found-count">${n} / ${clues.length}</span></div>${insightHTML()}<div class="invest-bottom"><div class="compass-control"><button data-action="panLeft" aria-label="向左环视">‹</button><input id="panRange" aria-label="环视位置" type="range" min="0" max="1000" value="${pan*1000}"><button data-action="panRight" aria-label="向右环视">›</button></div><div><button class="btn primary" data-action="finishInvest">${s().scene==='water'?'触动机关':'收起记录'}</button></div></div>`)}
function initPanorama(){const viewport=document.getElementById('panorama');if(!viewport)return;layoutPan();viewport.onpointerdown=e=>{if(e.button!==0&&e.pointerType==='mouse')return;drag={x:e.clientX,y:e.clientY,start:pan,moved:false};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging');};viewport.onpointermove=e=>{if(!drag)return;let dx=e.clientX-drag.x;if(Math.abs(dx)>5||Math.abs(e.clientY-drag.y)>5)drag.moved=true;const max=Math.max(1,viewport.querySelector('.pano-track').offsetWidth-viewport.clientWidth);pan=Math.max(0,Math.min(1,drag.start-dx/max));layoutPan();};viewport.onpointerup=e=>{if(!drag)return;const moved=drag.moved;drag=null;viewport.classList.remove('dragging');if(moved){render();}else{const rect=viewport.querySelector('.pano-track').getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;if(s().view==='chapterInvestigate'){ripple(e.clientX,e.clientY);send({type:'chapterCollect',x,y});return;}const hit=Game.hitTest(s().scene,x,y);ripple(e.clientX,e.clientY);if(hit)collect(hit);else toast('视线掠过此处，没有新的发现。');}};viewport.onpointercancel=()=>{drag=null;viewport.classList.remove('dragging')};}
function layoutPan(){const v=document.getElementById('panorama');if(!v)return;const t=v.querySelector('.pano-track'),w=Math.max(v.clientWidth,v.clientHeight*(s().view==='chapterInvestigate'?2.05:3));t.style.width=w+'px';t.style.transform=`translateX(${-pan*(w-v.clientWidth)}px)`;const input=document.getElementById('panRange');if(input)input.value=pan*1000;}
function ripple(x,y){const d=document.createElement('div');d.className='click-ripple';d.style.left=x+'px';d.style.top=y+'px';document.body.append(d);setTimeout(()=>d.remove(),700)}
function collect(id){const c=D.clues[id];if(s().observations[s().role].includes(id)){s().insight={id,role:s().role};render();return;}send({type:'collect',x:c.x,y:c.y});}
let echoAudio=null;
function playEcho(){try{echoAudio?.close();echoAudio=new (window.AudioContext||window.webkitAudioContext)();const ctx=echoAudio,t=ctx.currentTime;for(let i=0;i<16;i++){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=i<10?'sine':'triangle';const at=t+(i<8?i*.28:2.24+(i-8)*.18);osc.frequency.setValueAtTime(i<8?80:50+i*13,at);osc.frequency.exponentialRampToValueAtTime(28,at+.2);gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(.10,at+.008);gain.gain.exponentialRampToValueAtTime(.001,at+.23);osc.connect(gain).connect(ctx.destination);osc.start(at);osc.stop(at+.25);}setTimeout(()=>ctx.close(),5000);toast('先是齐整蹄声，随后错乱、撞击，最后归于寂静。');}catch{toast('回声记录：整齐蹄声 → 错乱 → 木裂与撞击 → 寂静。');}}
function renderMatch(){const r=s().role,ids=s().observations[r].filter(id=>(r==='A'?['cup','poem','footprints','testimony']:['latch','model','cup']).includes(id));shell(`${bg('boat')}<section class="panel-screen"><div class="eyebrow">两位真人 · 各自提交</div><h1>把你亲眼所见交给搭档</h1><p>你只能选择自己的记录。搭档从另一端提交；现场痕迹与机关路径吻合，才能继续。</p><div class="pair-grid"><div class="pair-column"><h2>${roleName(r)}的记录</h2>${ids.map(id=>`<button class="evidence-option ${s().match[r]===id?'selected':''}" data-match-role="${r}" data-match-id="${id}"><strong>${D.clues[id].name}</strong><small>${D.clues[id][r]}</small></button>`).join('')}</div><div class="pair-column"><h2>${roleName(s().net.partnerRole)}</h2><p>${s().match[s().net.partnerRole]?'搭档已递来一份记录。':'等待搭档提交他的记录。'}</p><p>${s().match[r]?'你的记录已送出，可以重新选择。':'请选择一份记录提交。'}</p></div></div><p class="help">${s().notice||''}</p></section>`)}
function renderQte(){const mirror=s().qte.type==='mirror',water=s().qte.type==='water',ready=s().view==='qteReady',steps=game.qteSteps(),step=steps[s().qte.step],active=s().role,partner=active==='A'?'B':'A';shell(`<div class="qte-world ${water?'water':'chase'} ${flash}"><div class="backdrop" style="background-image:url('${sceneImage(mirror?'market':water?'water':'dock')}')"></div><img class="qte-actor main" src="${poseImage(active,'action')}" alt="${roleName(active)}正在${water?'稳住船底机关':'追逐中行动'}"><img class="qte-actor partner" src="${poseImage(partner,'action')}" alt="搭档协同行动">${water?mechanismHTML(ready?'ready':'active')+'<div class="swing-rope"></div><div class="flood" style="--flood:18%"></div>':'<div class="rain-streaks"></div>'}</div><div class="qte-info"><div class="eyebrow">${mirror?'东市追镜 · 屋顶初遇':water?'危机一 · 船底灌水':'危机二 · 追过断桥'}</div><h1>${mirror?'接住这一面镜':water?'水在涨':'别让灯影断掉'}</h1><p>${mirror?'分清纸影与真人，配合搭档收住工匠和铜镜。':water?(s().role==='A'?(s().flags.support==='weight'?'按住不断滑落的配重与检修梯，为水中的搭档争取时间。':'顶住落下的舱门，把检修梯送到搭档手边。'):s().flags.support==='weight'?'巡捕已经踩住配重。幻术师有机会依次扳回铜轮。':'巡捕正顶着舱门。幻术师必须攥紧绳索，找到落脚处。'):(s().role==='A'?'沿着搭档给出的指引，追上披风的背影。':'在桥侧协助巡捕。每一次折光、投绳与配重，都决定搭档下一步能落在哪里。')}</p></div><div class="qte-prompt">${ready?`<div class="eyebrow">${roleName(active)}的动作</div><p>画面开始后，按提示键或点击动作按钮。<br>每个动作单独判定，错过仍会继续剧情。</p><button class="btn primary" data-action="beginQte">${s().net?.ready?.[s().role]?'已准备，等待搭档':'准备好了 · 等双方开始'}</button>`:`<div class="qte-ring">${step[1]}</div><strong>${step[0]}</strong><div class="qte-time"><i></i></div><button class="btn primary" data-action="hitQte" ${qteLock?'disabled':''}>${step[2]}　[${step[1]}]</button><div class="qte-dots">${steps.map((_,i)=>`<i class="${i<s().qte.step?'done':''}"></i>`).join('')}</div>`}</div>${flash?`<div class="qte-feedback">${flash==='hit'?'稳住了':'慢了一步'}</div>`:''}`);}
function qteDuration(){return (s().slowQte?11000:6500)+(s().qte?.type==='chase'&&s().flags.mirrorSignal?1500:0)}
function startClock(){const token=s().qte.type+':'+s().qte.step;if(token!==stepToken){stepToken=token;qteRemaining=Math.max(0,(s().qte.deadline||Date.now()+qteDuration())-Date.now());}qteStamp=performance.now();function tick(now){if(s().view!=='qte')return;const dt=Math.min(100,now-qteStamp);qteStamp=now;if(!qteLock){qteRemaining=Math.max(0,s().qte.deadline-(Date.now()+clockOffset));const t=document.querySelector('.qte-time i');if(t)t.style.transform=`scaleX(${Math.max(0,qteRemaining/qteDuration())})`;const water=document.querySelector('.flood');if(water)water.style.height=(18+s().qte.step*9+(1-qteRemaining/qteDuration())*10)+'%';if(qteRemaining<=0){resolveQte(false);return;}}frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)}
function resolveQte(ok){if(s().view!=='qte'||s().waiting||qteLock)return;qteLock=true;cancelAnimationFrame(frame);flash=ok?'hit':'miss';const step=s().qte.step,key=ok?game.qteSteps()[step][1]:'';render();send({type:'qte',step,key});setTimeout(()=>{qteLock=false;flash='';render();},480)}
function renderDeduce(){const d=s().deduction;const groups=[['suspect','是谁动了手',[['host','诗社主持'],['boatwoman','船娘'],['accident','无人谋害，只是意外']]],['method','密室如何成立',[['mechanism','香气致昏 → 下层溺杀 → 升降移尸 → 铜丝扣闩'],['poison','杯中下毒，再从窗边离开'],['unknown','只确定证词矛盾，暂不复原机关']]],['motive','为什么要杀人',[['poem','阻止异常诗稿公开，保住权贵与诗社的前途'],['ledger','仅为抵押欠账灭口'],['unknown','动机尚待核实']]]];shell(`${bg('temple')}<section class="panel-screen"><div class="eyebrow">共同节点 · 结案推理</div><h1>把这一夜接起来</h1><p>人、手法、动机须同时被证据支撑。资料不足时，也可以保留疑点封卷。${s().debug?'证据完整度 '+s().stats.EVIDENCE+'/10':''}</p>${groups.map(([key,title,opts])=>`<section class="deduction-group"><h2>${title}</h2><div class="choice-row">${opts.map(([id,text])=>`<button class="choice ${d[key]===id?'selected':''}" data-deduce="${key}" data-value="${id}" ${(id==='mechanism'&&!game.precise())||(key==='motive'&&id==='poem'&&!s().evidence.includes('ledger'))?'disabled':''}>${id==='mechanism'&&!game.precise()?'机关的完整路径尚未拼合':key==='motive'&&id==='poem'&&!s().evidence.includes('ledger')?'尚未取得夹在账页里的异常诗稿':text}${id==='mechanism'&&!game.precise()?`<small class="lock-reason">需要 证据完整度 ≥ 6（当前 ${s().stats.EVIDENCE}）；门闩记录${s().evidence.includes('latch')?'已取得':'未取得'}；铜轮记录${s().evidence.includes('gear')?'已取得':'未取得'}</small>`:''}</button>`).join('')}</div></section>`).join('')}<p class="help">${s().notice||''}${s().net?.partnerVote?'<br>搭档已提交：'+Object.values(s().net.partnerVote).map(v=>({host:'诗社主持',boatwoman:'船娘',accident:'意外',mechanism:'沉水机关',poison:'毒杀',unknown:'尚待查明',ledger:'掩盖账目',poem:'封藏异常诗稿'}[v])).join(' · '):''}${s().waiting?'<br>你的判断已提交，等待搭档核对。':''}</p><button class="btn primary" data-action="submit" ${d.suspect&&d.method&&d.motive?'':'disabled'}>提交给搭档共同确认</button></section>`)}
function renderEnd(){const f=s().flags,truth=s().stats.TRUTH>=15,title=f.correct?'月沉，有人拨轮':f.partial?'灯下尚有疑处':'无人答完的诗';shell(`${bg('lake')}<section class="outro"><div class="eyebrow">曲江沉月案 · 夜尽之前</div><h1>${title}</h1><p>${f.correct?'两份调查终于接成一线。主持先迷昏诗人，在船底将他溺死，换上干燥外袍，再借活动席板与配重将尸体送回锁室。诗人准备公开的异常诗稿，会牵连主持背后的权贵。账页只是掩饰，稿上那片废弃的长安仍无法解释。':f.partial?'主持已被列为首要嫌疑人。两人的调查能够指出谎言，却还不能把手法与动机完整连起来。案卷留下空白，等待下一次核对。':'这一指认未能得到证据支撑。船上仍有人在说谎，案子暂时封卷。两人约定，不能用一个容易的答案换掉死者的一夜。'}</p><p>${f.saved?'幻术师低头看了一眼手腕。那里的红痕，是巡捕将他拉出水舱时留下的。':'幻术师把石屑收进衣袖。他独自脱身的那条暗渠，画在任何一份新城图上都显得多余。'}</p><p>${truth?'幻术师记得落水时，倒影里似乎缺了一座塔。他还没有向巡捕说起。':'水中的灯比岸上的灯晚亮了一瞬。风过曲江，涟漪把那点差异带远。'}</p>${!truth?`<p class="scene-condition ending-condition">更清晰的倒影未触发 · 需要 真相认知 ≥ 15（当前 ${s().stats.TRUTH}）</p>`:''}<span class="tag">${f.correct?'完整破案':f.partial?'保留疑点':'错指成案'}</span>${truth?'<span class="tag">共同目击 · 倒影缺角</span>':''}<span class="tag">${s().role==='A'?'巡捕 · 全程固定身份':'幻术师 · 全程固定身份'}</span><div class="choice-row"><button class="btn" data-action="notebook">翻阅共同案卷</button><button class="btn primary" data-action="chapterContinue">回到水边 · 继续长安的故事</button></div></section>`,truth?'ending-truth':'');}
function notebook(){if(s().campaign?.chapter!=='qujiang')return U.notebook(s());const shared=s().flags.validated||s().view==='end',ids=shared?s().evidence:s().observations[s().role];return `<p class="help">${shared?'双方已会合，现可核对共同记录。':'这里只收录当前角色亲眼看见、亲耳问到的发现。'}</p><div class="notebook-grid">${ids.length?ids.map(id=>`<article class="evidence-entry">${preview(id)}<h3>${D.clues[id].name}</h3><p>${D.clues[id][s().role]}</p><small class="muted">${s().observations.A.includes(id)?'巡捕已记录　':''}${s().observations.B.includes(id)?'幻术师已记录':''}</small></article>`).join(''):'<p class="help">案卷还没有翻开。先进入画舫调查。</p>'}</div>`}
function progress(){if(s().campaign?.chapter!=='qujiang')return `<div class="eyebrow">${P.current(s()).title}</div><p class="help">${game.task()}</p><p class="help">我的现场记录：${s().campaign.found[s().role].length}；搭档记录：${s().net?.campaignPartnerCount||0}<br>章节问询：${s().campaign.witness.A?'巡捕已完成':'巡捕未完成'} · ${s().campaign.witness.B?'幻术师已完成':'幻术师未完成'}</p>`;return `<div class="pair-grid">${['A','B'].map(r=>`<div class="pair-column"><h2>${roleName(r)}</h2><p class="help">${s().flags['intro'+r]?'✓':'○'} 独立开场<br>${s().flags['cabin'+r]?'✓':'○'} 船舱勘验<br>${s().flags[r==='A'?'witness':'workshop']?'✓':'○'} ${r==='A'?'船娘问询':'旧图核验'}<br>已记录 ${r===s().role?s().observations[r].length:s().net?.partnerCount||0} 项观察</p></div>`).join('')}</div><p class="help">${game.task()}<br>当前角色的选择会改变搭档的追问、机关支援和追逐动作。两份必需调查完成后，在画舫会合验证。</p>`}
function modalHTML(){let title='',body='';if(modal==='checkpoints'){title='共留此夜 · 自动存档';const pending=s().net?.loadRequest;body=`<p class="help">关键选择前自动保存双方的剧情、线索与数值。读取需搭档确认；确认后两人一起回到该节点，之后的进度与存档将被替换。存档随当前房间保留 7 天（从最后活动起算）。</p>${pending?`<section class="checkpoint-request"><p>${roleName(pending.by)}提议回到「${s().net.checkpoints.find(c=>c.id===pending.id)?.label||'存档点'}」。</p>${pending.by!==s().role?'<button class="btn primary" data-action="loadAgree">同意 · 双方回到此处</button>':'<p class="help">等待搭档确认…</p>'}<button class="btn" data-action="loadCancel">${pending.by===s().role?'撤回':'暂不读档'}</button></section>`:''}<div class="checkpoint-list">${(s().net?.checkpoints||[]).slice().reverse().map(c=>`<article class="checkpoint-entry"><div><h3>${c.label}</h3><small>自动存档 · ${new Date(c.time).toLocaleString('zh-CN')}</small></div><button class="btn" data-action="loadRequest" data-id="${c.id}" ${pending?'disabled':''}>请求共同读档</button></article>`).join('')||'<p class="help">尚未到达存档点。画舫分工、问询与传信、水舱救援、救人与追凶、断桥协作都会自动留下存档。</p>'}</div>`;}if(modal==='notebook'){title='夜行案卷';body=notebook();}if(modal==='progress'){title='一夜，两条路径';body=progress();}if(modal==='help'){title='如何进入这场夜色';body=`<p class="help">开始时选择巡捕或幻术师。地图上的建筑没有文字标牌，移上去会浮起发光；点击进入。金色微光提示当前主线目的地。<br><br>身份选定后全程固定。两位真人各用一个浏览器，打开邀请链接后加入同一房间。两条线路独立调查，共同节点等待双方到场。只能作出自己角色的决定。<br><br>调查画面铺满屏幕：按住鼠标或手指左右拖动，松开后点击物件。没有线索圆点，也不提前显示名称。左右方向键和底部滑杆同样可以环视；键盘 Tab 可聚焦物件。<br><br>QTE 先准备、再开始。按提示键或点击动作按钮；每次只判定一个动作，按错或超时会改变结果。双方准备后一起计时，切离页面不会暂停；两人的动作都会影响结果。<br><br>每次操作保存到联机服务。刷新原页面可恢复身份。搭档需要连接同一服务；关闭服务时双方都会断线。</p>`;}if(modal==='settings'){title='设置与数值';body=`<label class="setting-row"><p>预览选项数值<small>选择后的实际变化始终提示；开启后还可在选择前预览数值</small></p><input type="checkbox" data-setting="debug" ${s().debug?'checked':''}></label><label class="setting-row"><p>舒缓 QTE<small>将每步操作时间延长至 11 秒</small></p><input type="checkbox" data-setting="slowQte" ${s().slowQte?'checked':''}></label>${s().debug?Object.entries(s().stats).map(([k,v])=>`<div class="stat"><span>${statNames[k]}</span><div class="stat-meter"><i style="width:${k==='EVIDENCE'?v*10:v}%"></i></div><span>${v}</span></div>`).join('')+'<p class="help">两人的信任分别记录，代表各自愿意向搭档交付秘密与判断的程度。<br>真相认知、幻境依恋、幻境失稳的范围为 0–100；证据完整度为 0–10。</p>':''}<button class="quiet" data-action="newGame">离开当前房间</button>`;}if(modal==='restart'){title='另起一夜';body='<p class="help">离开只会清除本标签页的连接信息。房间中的身份仍被保留，不可在同一房间换角色。要另开一局，请创建新房间。</p><button class="btn primary" data-action="confirmNew">离开当前房间</button>';}
return `<div class="modal" role="dialog" aria-modal="true" aria-label="${title}"><div class="modal-card"><div class="modal-head"><h2>${title}</h2><button class="quiet" data-action="close" aria-label="关闭">×</button></div>${body}</div></div>`;}
let fragmentSelection=[];function selectFragment(el){const id=el.dataset.fragment;if(fragmentSelection.includes(id))return;fragmentSelection.push(id);el.classList.add('picked');if(fragmentSelection.length===3){const container=document.getElementById('fragments');for(const i of fragmentSelection)container.appendChild(container.querySelector('[data-fragment="'+i+'"]'));fragmentSelection=[];container.querySelectorAll('.picked').forEach(x=>x.classList.remove('picked'));}}
function initFragments(){fragmentSelection=[];const box=document.getElementById('fragments');if(!box)return;let dragged=null;box.ondragstart=e=>{dragged=e.target.closest('[data-fragment]');};box.ondragover=e=>e.preventDefault();box.ondrop=e=>{e.preventDefault();const target=e.target.closest('[data-fragment]');if(dragged&&target&&dragged!==target)box.insertBefore(dragged,target);dragged=null;};}
function openModal(id){lastFocus=document.activeElement;modal=id;render();}
app.addEventListener('click',e=>{
 const el=e.target.closest('[data-action],[data-role],[data-location],[data-choice],[data-object],[data-match-id],[data-deduce],[data-campaign-object],[data-fragment]');if(!el)return;
 if(el.dataset.campaignObject){if(e.detail===0){const c=P.current(s()).clues[s().role].find(x=>x.id===el.dataset.campaignObject);send({type:'chapterCollect',x:c.x,y:c.y});}return;}if(el.dataset.fragment){selectFragment(el);return;}if(el.dataset.object){if(e.detail===0)collect(el.dataset.object);return;}
 if(el.dataset.role){selectedRole=el.dataset.role;render();return;}
 if(el.dataset.location){send({type:'location',id:el.dataset.location});return;}
 if(el.dataset.choice!==undefined){send({type:'next',choice:+el.dataset.choice});return;}
 if(el.dataset.matchId){send({type:'match',id:el.dataset.matchId});return;}
 if(el.dataset.deduce){send({type:'deduce',key:el.dataset.deduce,value:el.dataset.value});return;}
 switch(el.dataset.action){
 case 'checkpoints':case 'notebook':case 'settings':case 'help':case 'progress':openModal(el.dataset.action);break;
 case 'loadRequest':send({type:'loadRequest',id:el.dataset.id});break;
 case 'loadAgree':send({type:'loadAgree'});break;
 case 'loadCancel':send({type:'loadCancel'});break;
 case 'close':modal=null;render();break;
 case 'createRoom':enterRoom(false);break;
 case 'joinRoom':enterRoom(true);break;
 case 'copyInvite':{const input=document.querySelector('.invite-link');input.select();navigator.clipboard?.writeText(input.value).then(()=>toast('邀请地址已复制')).catch(()=>toast('请复制选中的邀请地址。'));break;}
 case 'resume':if(readSave())connect(readSave());break;
 case 'newGame':openModal('restart');break;
 case 'confirmNew':events?.close();clearTimeout(pollTimer);pollGeneration++;connection=null;game=new Game();modal=null;selectedRole=null;panScene='';stepToken='';sessionStorage.removeItem(SAVE);render();break;
 case 'chapterTravel':send({type:'location',id:P.current(s()).site});break;
 case 'chapterWitness':send({type:'location',id:P.current(s()).witness});break;
 case 'replayEcho':playEcho();break;
 case 'chapterExperiment':case 'chapterMap':case 'chapterMeet':case 'drumConfirm':case 'chapterContinue':send({type:el.dataset.action});break;
 case 'chapterPuzzle':case 'chapterVerdict':send({type:el.dataset.action,answer:+el.dataset.answer});break;
 case 'finalSubmit':send({type:'finalSubmit',id:el.dataset.id});break;
 case 'fragmentSubmit':send({type:'chapterPuzzle',answer:[...document.querySelectorAll('#fragments [data-fragment]')].map(x=>x.dataset.fragment).join(',')});break;
 case 'meet':send({type:'location',id:'boat'});break;
 case 'finishInvest':send({type:'finishInvest'});break;
 case 'toggleSceneUI':sceneUIHidden=!sceneUIHidden;render();break;
 case 'dismissInsight':s().insight=null;render();break;
 case 'panLeft':pan=Math.max(0,pan-.15);layoutPan();break;
 case 'panRight':pan=Math.min(1,pan+.15);layoutPan();break;
 case 'beginQte':send({type:'beginQte'});break;
 case 'hitQte':resolveQte(true);break;
 case 'submit':send({type:'submit'});break;
 }
});
document.addEventListener('keydown',e=>{if(s().view==='chapterInvestigate'&&!modal&&!e.repeat&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&e.key?.toLowerCase()==='h'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName)){e.preventDefault();sceneUIHidden=!sceneUIHidden;render();}});
app.addEventListener('input',e=>{if(e.target.id==='panRange'){pan=+e.target.value/1000;layoutPan();}});
app.addEventListener('change',e=>{if(e.target.dataset.setting){if(connection)send({type:'setting',key:e.target.dataset.setting,value:e.target.checked});else{s()[e.target.dataset.setting]=e.target.checked;render();}}});
document.addEventListener('keydown',e=>{
 if(modal){if(e.key==='Escape'){modal=null;render();}if(e.key==='Tab'){const nodes=[...app.querySelectorAll('.modal button,.modal input')].filter(x=>!x.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}
 if(e.repeat)return;
 if(s().view==='qte'&&!s().waiting&&['a','d','w'].includes(e.key.toLowerCase())){e.preventDefault();resolveQte(e.key.toUpperCase()===game.qteSteps()[s().qte.step][1]);return;}
 if(['investigate','chapterInvestigate'].includes(s().view)&&['ArrowLeft','ArrowRight'].includes(e.key)&&e.target.type!=='range'){e.preventDefault();pan=Math.max(0,Math.min(1,pan+(e.key==='ArrowLeft'?-.08:.08)));layoutPan();}
 const l=e.target.closest?.('[data-location]');if(l&&['Enter',' '].includes(e.key)){e.preventDefault();send({type:'location',id:l.dataset.location});}
});
window.addEventListener('resize',layoutPan);
app.addEventListener('pointermove',e=>{if(s().view!=='dialog'||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;app.style.setProperty('--look-x',((e.clientX/window.innerWidth-.5)*12)+'px');app.style.setProperty('--look-y',((e.clientY/window.innerHeight-.5)*5)+'px');});
// Begin loading the art used immediately; other scene images load on first visit.
['lake','boat','cabin','water'].forEach(id=>{const i=new Image();i.src=sceneImage(id)});
if(location.protocol!=='file:')fetch('/api/host').then(r=>r.json()).then(d=>{hostUrls=d.urls||[];if(s().view==='lobby')render();}).catch(()=>{});
if(readSave()&&location.protocol!=='file:')connect(readSave());else render();
})();
