(()=>{
'use strict';
const D=window.GAME_DATA,app=document.getElementById('app'),SAVE='changan-demo-v2';
let game=new Game(),modal=null,pan=0,panScene='',drag=null,toastTimer=null,frame=0,qteRemaining=0,qteStamp=0,qteLock=false,stepToken='',flash='',lastFocus=null;
const s=()=>game.s;
const sceneImage=id=>'assets/scenes/'+id+'.png';
const poseImage=(who,pose='idle')=>{
 if(who==='A'||who==='B')return pose==='idle'?'assets/'+who.toLowerCase()+'.png':'assets/poses/'+who.toLowerCase()+'-'+pose+'.png';
 const variants={host:'defend',boatwoman:'point',poet:'write'};
 return variants[who]&&pose!=='idle'?'assets/poses/'+who+'-'+variants[who]+'.png':'assets/'+who+'.png';
};
const roleName=r=>D.roles[r].name;
const fmt=d=>Object.entries(d||{}).filter(([,v])=>v).map(([k,v])=>k+' '+(v>0?'+':'')+v).join(' · ');
function readSave(){try{const v=JSON.parse(localStorage.getItem(SAVE));return v&&v.version===2&&v.stats&&v.flags&&v.observations&&['map','end'].includes(v.view)?v:null}catch{return null}}
function save(){if(!['map','end'].includes(s().view))return;try{localStorage.setItem(SAVE,JSON.stringify(s()))}catch{}}
function toast(text){document.querySelector('.toast')?.remove();clearTimeout(toastTimer);const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);toastTimer=setTimeout(()=>el.remove(),3000)}
function effectToast(before){if(!s().debug)return;const d={};for(const k in s().stats){let n=s().stats[k]-before[k];if(n)d[k]=n;}if(Object.keys(d).length)toast(fmt(d));}
function particles(){return '<div class="particles">'+Array.from({length:15},(_,i)=>`<i style="left:${(i*23+5)%100}%;top:${(i*17+25)%95}%;animation-delay:${i*.6}s"></i>`).join('')+'</div>'}
function bg(id,cls=''){return `<div class="backdrop ${cls}" style="background-image:url('${sceneImage(id)}')"></div><div class="vignette"></div>${particles()}`}
function header(){return `<header class="topbar"><div class="brand">长安未醒<small>曲江沉月案 · 双影</small></div>${s().view!=='start'?`<span class="role-tag">${roleName(s().role)}视角</span>`:''}<nav class="nav">${s().view!=='start'?'<button data-action="notebook">案卷</button><button data-action="progress">双人进度</button>':''}<button data-action="settings">设置</button><button data-action="help">玩法</button></nav></header>`}
function shell(body,cls=''){app.innerHTML=`<main class="${cls}">${body}${header()}<div class="grain"></div></main>${modal?modalHTML():''}`;initPanorama();if(s().view==='qte')startClock();if(modal){const focusable=app.querySelector('.modal button');focusable?.focus();}save();}
function render(){cancelAnimationFrame(frame);const views={start:renderStart,map:renderMap,dialog:renderDialog,investigate:renderInvestigate,match:renderMatch,qteReady:renderQte,qte:renderQte,deduce:renderDeduce,end:renderEnd};(views[s().view]||renderStart)();}
function renderStart(){shell(`${bg('lake')}<div class="start-content"><div class="start-copy"><span class="seal">壹 · 沉月</span><div class="eyebrow">今夜，你从谁的眼中看长安</div><h1>长安未醒</h1><h2>曲江沉月案</h2><p>一封未署名的信，一场未申报的幻戏。<br>有人倒在反锁的船舱里。<br>两个人，看见了同一夜的两面。</p>${readSave()?'<button class="btn resume" data-action="resume">续上次的夜行</button>':''}</div><div class="role-cards">${['A','B'].map(r=>`<button class="role-card" data-role="${r}" aria-label="选择${roleName(r)}"><img src="assets/${r.toLowerCase()}.png" alt="${roleName(r)}"><div class="role-card-copy"><span>${r==='A'?'大理寺':'幻术院'}</span><h3>${roleName(r)}</h3><span>${D.roles[r].subtitle}</span><b>以此身份入长安　↗</b></div></button>`).join('')}</div></div><div class="start-footer">单机双视角 · 在地图中切换搭档 · 会合时互相验证 · 自动保存至最近地图节点</div>`)}
function recommended(){if(!s().flags.murder||!s().flags['cabin'+s().role])return 'boat';if(s().role==='A'&&!s().flags.witness)return 'shrine';if(s().role==='B'&&!s().flags.workshop)return 'academy';return game.readyToMeet()?'boat':null;}
function renderMap(){const rec=recommended();const flags=s().flags;shell(`<div class="map-stage"><svg class="world-svg" viewBox="0 0 1672 941" aria-label="曲江区域手绘地图" preserveAspectRatio="xMidYMid slice"><defs>${D.locations.map(l=>`<clipPath id="clip-${l.id}"><polygon points="${l.p}"/></clipPath>`).join('')}</defs><image class="map-base" href="assets/map.png" width="1672" height="941"/>${D.locations.map(l=>`<g class="map-region ${rec===l.id?'recommended':''}" role="button" tabindex="0" aria-label="前往${D.scenes[l.id]}" data-location="${l.id}"><image class="map-piece" href="assets/map.png" width="1672" height="941" clip-path="url(#clip-${l.id})"/><polygon class="map-edge" points="${l.p}"/></g>`).join('')}</svg></div><div class="map-caption">月过曲江 · 更深未眠</div><div class="map-hud"><div class="eyebrow">${roleName(s().role)} · ${flags.murder?'分头夜查':'初至曲江'}</div><h2>${flags.validated?'眼见之下':game.routeDone(s().role)?'等另一份答案':'沿着留下的痕迹'}</h2><p>${game.task()}</p><div class="progress-dots">${[flags.murder,flags.cabinA,flags.witness,flags.cabinB,flags.workshop,flags.validated,flags.chaseDone].map(x=>`<i class="${x?'done':''}"></i>`).join('')}</div><small>移向建筑或画舫，图像会浮起。点击进入。</small></div><div class="map-controls"><button class="btn" data-action="switch">换到${roleName(s().role==='A'?'B':'A')}视角 ⇄</button>${game.readyToMeet()?`<button class="btn primary" data-action="meet">${flags.validated?'返回画舫':'会合 · 验证两份发现'}</button>`:''}</div><div class="save-indicator">地图节点已保存</div>`)}
function character(who,pose,side,active){if(!['A','B','host','poet','boatwoman'].includes(who))return '';return `<img class="character ${side} ${active?'active':'idle'} ${pose==='action'?'action':''}" src="${poseImage(who,pose)}" alt="${D.speakers[who]}" draggable="false">`}
function renderDialog(){const l=game.currentLine();if(!l)return;s().scene=game.sceneFor(s().event);const isPartner=['A','B'].includes(l.who),npc=['host','poet','boatwoman'].includes(l.who);let chars='';if(isPartner){chars=character(l.who,l.pose,l.who==='A'?'left':'right',true);if(['feast','reunion','waterEntry','alarm','afterWater','beforeChase','afterChase'].includes(s().event))chars+=character(l.who==='A'?'B':'A','examine',l.who==='A'?'right':'left',false);}else if(npc){chars=character(l.who,l.pose,'right',true)+character(s().role,'examine','left',false);}
shell(`${bg(s().scene)}<div class="scene-mark">${D.scenes[s().scene]}${s().event.startsWith('intro')&&s().flags.murder?' · 同一夜稍早':''}</div><div class="dialog-world">${chars}</div><section class="dialog-box"><div class="speaker">${D.speakers[l.who]||'夜色'}${l.choices?`<span class="turn-hint">此刻由${D.speakers[l.who]||roleName(s().role)}决定</span>`:''}</div><p class="dialog-text ${l.who==='n'?'narration':''}">${l.text}</p><div class="choice-row">${l.choices?l.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${c.text}${c.hint?`<small>${c.hint}</small>`:''}${s().debug?`<div class="delta">${fmt(c.effects.stats)||'数值不变'}</div>`:''}</button>`).join(''):'<button class="choice next" data-choice="0">继续　→</button>'}</div></section>`,'page-fade');}
function sceneClues(){return Object.entries(D.clues).filter(([,c])=>c.scene===s().scene&&c.x!==undefined);}
function preview(id){const c=D.clues[id];if(c.x===undefined)return `<div class="object-preview"><img src="${sceneImage(c.scene)}" alt="" style="width:100%;height:100%;object-fit:cover;left:0;top:0"></div>`;return `<div class="object-preview"><img src="${sceneImage(c.scene)}" alt="物件细节" style="width:${100/c.w}%;height:${100/c.h}%;left:${-(c.x-c.w/2)/c.w*100}%;top:${-(c.y-c.h/2)/c.h*100}%"></div>`;}
function insightHTML(){if(!s().insight)return '';const {id,role}=s().insight,c=D.clues[id];return `<aside class="insight" role="status">${preview(id)}<div class="eyebrow">${roleName(role)}的观察</div><p>${c[role]}</p>${s().debug?`<div class="delta">${c.score?'EVIDENCE +'+c.score:''} ${c.truth?'TRUTH +'+c.truth:''}（同一证物只计一次）</div>`:''}<button class="quiet" data-action="dismissInsight">记入案卷 · 继续查看</button></aside>`;}
function renderInvestigate(){if(panScene!==s().scene){panScene=s().scene;pan=s().scene==='cabin'&&s().role==='B'?1:0;}const clues=sceneClues(),n=clues.filter(([id])=>s().observations[s().role].includes(id)).length;shell(`<div id="panorama" class="panorama"><div class="pano-track"><img class="pano-image" src="${sceneImage(s().scene)}" alt="${D.scenes[s().scene]}全景，可拖动环视" draggable="false">${clues.map(([id,c])=>`<button class="object-hit ${s().observations[s().role].includes(id)?'found':''}" data-object="${id}" aria-label="查看此处${s().observations[s().role].includes(id)?'，已记录':''}" style="left:${c.x*100}%;top:${c.y*100}%;width:${c.w*100}%;height:${c.h*100}%"></button>`).join('')}</div></div><div class="invest-head"><p>${roleName(s().role)} · 静看${s().scene==='cabin'?'舱中':'水下'}</p><small>按住画面拖动环视；直接点击可疑物件。</small><span class="found-count">${n} / ${clues.length}</span></div>${insightHTML()}<div class="invest-bottom"><div class="compass-control"><button data-action="panLeft" aria-label="向左环视">‹</button><input id="panRange" aria-label="环视位置" type="range" min="0" max="1000" value="${pan*1000}"><button data-action="panRight" aria-label="向右环视">›</button></div><div><button class="btn" data-action="switch">换视角</button> <button class="btn primary" data-action="finishInvest">${s().scene==='water'?'触动机关':'收起记录'}</button></div></div>`)}
function initPanorama(){const viewport=document.getElementById('panorama');if(!viewport)return;layoutPan();viewport.onpointerdown=e=>{if(e.button!==0&&e.pointerType==='mouse')return;drag={x:e.clientX,y:e.clientY,start:pan,moved:false};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging');};viewport.onpointermove=e=>{if(!drag)return;let dx=e.clientX-drag.x;if(Math.abs(dx)>5||Math.abs(e.clientY-drag.y)>5)drag.moved=true;const max=Math.max(1,viewport.querySelector('.pano-track').offsetWidth-viewport.clientWidth);pan=Math.max(0,Math.min(1,drag.start-dx/max));layoutPan();};viewport.onpointerup=e=>{if(!drag)return;const moved=drag.moved;drag=null;viewport.classList.remove('dragging');if(!moved){const rect=viewport.querySelector('.pano-track').getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;const hit=Game.hitTest(s().scene,x,y);ripple(e.clientX,e.clientY);if(hit)collect(hit);else toast('视线掠过此处，没有新的发现。');}};viewport.onpointercancel=()=>{drag=null;viewport.classList.remove('dragging')};}
function layoutPan(){const v=document.getElementById('panorama');if(!v)return;const t=v.querySelector('.pano-track'),w=Math.max(v.clientWidth,v.clientHeight*3);t.style.width=w+'px';t.style.transform=`translateX(${-pan*(w-v.clientWidth)}px)`;const input=document.getElementById('panRange');if(input)input.value=pan*1000;}
function ripple(x,y){const d=document.createElement('div');d.className='click-ripple';d.style.left=x+'px';d.style.top=y+'px';document.body.append(d);setTimeout(()=>d.remove(),700)}
function collect(id){const before={...s().stats};if(!game.collect(id)){s().insight={id,role:s().role};}render();effectToast(before);}
function renderMatch(){const candidates={A:s().observations.A.filter(id=>['cup','poem','footprints','testimony'].includes(id)),B:s().observations.B.filter(id=>['latch','model','cup'].includes(id))};shell(`${bg('boat')}<section class="panel-screen"><div class="eyebrow">共同节点 · 证据互证</div><h1>让两份发现相遇</h1><p>从两人的独立记录里，各选出一项。只有现场痕迹与机关路径能够互相解释，两人才会一起下到水舱。</p><div class="pair-grid">${['A','B'].map(r=>`<div class="pair-column"><h2>${roleName(r)}的记录</h2>${candidates[r].map(id=>`<button class="evidence-option ${s().match[r]===id?'selected':''}" data-match-role="${r}" data-match-id="${id}"><strong>${D.clues[id].name}</strong><small>${D.clues[id][r]}</small></button>`).join('')}</div>`).join('')}</div><div class="match-footer"><p class="help">${s().flags.delegated?'幻术师主动把拆验结果放在桌上。':'幻术师将封存时的痕迹与旧图一同摊开。'}${s().debug?'<br>验证成功：TA +3 · TB +3 · EVIDENCE +1':''}</p><button class="btn primary" data-action="validate" ${s().match.A&&s().match.B?'':'disabled'}>验证 · 下到水舱</button></div></section>`)}
function renderQte(){const water=s().qte.type==='water',ready=s().view==='qteReady',steps=game.qteSteps(),step=steps[s().qte.step],active=water?'B':s().lead,partner=active==='A'?'B':'A';shell(`<div class="qte-world ${water?'water':'chase'} ${flash}"><div class="backdrop" style="background-image:url('${sceneImage(water?'water':'dock')}')"></div><img class="qte-actor main" src="${poseImage(active,'action')}" alt="${roleName(active)}正在${water?'稳住船底机关':'追逐中行动'}"><img class="qte-actor partner" src="${poseImage(partner,'action')}" alt="搭档协同行动">${water?'<div class="swing-rope"></div><div class="flood" style="--flood:18%"></div>':'<div class="rain-streaks"></div>'}</div><div class="qte-info"><div class="eyebrow">${water?'危机一 · 船底灌水':'危机二 · 追过断桥'}</div><h1>${water?'水在涨':'别让灯影断掉'}</h1><p>${water?(s().flags.support==='weight'?'巡捕已经踩住配重。幻术师有机会依次扳回铜轮。':'巡捕正顶着舱门。幻术师必须攥紧绳索，找到落脚处。'):(s().lead==='A'?'沿着搭档给出的指引，追上披风的背影。':'在桥侧协助巡捕。每一次折光、投绳与配重，都决定搭档下一步能落在哪里。')}</p></div><div class="qte-prompt">${ready?`<div class="eyebrow">${roleName(active)}的动作</div><p>画面开始后，按提示键或点击动作按钮。<br>每个动作单独判定，错过仍会继续剧情。</p><button class="btn primary" data-action="beginQte">准备好了 · 开始</button>`:`<div class="qte-ring">${step[1]}</div><strong>${step[0]}</strong><div class="qte-time"><i></i></div><button class="btn primary" data-action="hitQte" ${qteLock?'disabled':''}>${step[2]}　[${step[1]}]</button><div class="qte-dots">${steps.map((_,i)=>`<i class="${i<s().qte.step?'done':''}"></i>`).join('')}</div>`}</div>${flash?`<div class="qte-feedback">${flash==='hit'?'稳住了':'慢了一步'}</div>`:''}`);}
function qteDuration(){return (s().slowQte?11000:6500)+(s().qte?.type==='chase'&&s().flags.mirrorSignal?1500:0)}
function startClock(){const token=s().qte.type+':'+s().qte.step;if(token!==stepToken){stepToken=token;qteRemaining=qteDuration();}qteStamp=performance.now();function tick(now){if(s().view!=='qte')return;const dt=Math.min(100,now-qteStamp);qteStamp=now;if(!modal&&!document.hidden&&!qteLock){qteRemaining-=dt;const t=document.querySelector('.qte-time i');if(t)t.style.transform=`scaleX(${Math.max(0,qteRemaining/qteDuration())})`;const water=document.querySelector('.flood');if(water)water.style.height=(18+s().qte.step*9+(1-qteRemaining/qteDuration())*10)+'%';if(qteRemaining<=0){resolveQte(false);return;}}frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)}
function resolveQte(ok){if(s().view!=='qte'||qteLock||modal)return;qteLock=true;cancelAnimationFrame(frame);flash=ok?'hit':'miss';render();setTimeout(()=>{const before={...s().stats};game.qteResult(ok);qteLock=false;flash='';render();effectToast(before);},480)}
function renderDeduce(){const d=s().deduction;const groups=[['suspect','是谁动了手',[['host','诗社主持'],['boatwoman','船娘'],['accident','无人谋害，只是意外']]],['method','密室如何成立',[['mechanism','香气致昏 → 席板沉水 → 回升复位 → 铜丝扣闩'],['poison','杯中下毒，再从窗边离开'],['unknown','只确定证词矛盾，暂不复原机关']]],['motive','为什么要杀人',[['ledger','阻止诗人公开画舫抵押与欠账'],['poem','争夺诗会名次'],['unknown','动机尚待核实']]]];shell(`${bg('temple')}<section class="panel-screen"><div class="eyebrow">共同节点 · 结案推理</div><h1>把这一夜接起来</h1><p>人、手法、动机须同时被证据支撑。资料不足时，也可以保留疑点封卷。${s().debug?'证据完整度 '+s().stats.EVIDENCE+'/10':''}</p>${groups.map(([key,title,opts])=>`<section class="deduction-group"><h2>${title}</h2><div class="choice-row">${opts.map(([id,text])=>`<button class="choice ${d[key]===id?'selected':''}" data-deduce="${key}" data-value="${id}" ${(id==='mechanism'&&!game.precise())||(key==='motive'&&id==='ledger'&&!s().evidence.includes('ledger'))?'disabled':''}>${id==='mechanism'&&!game.precise()?'机关的完整路径尚未拼合':key==='motive'&&id==='ledger'&&!s().evidence.includes('ledger')?'账目的来龙去脉尚不完整':text}${id==='mechanism'&&!game.precise()?'<small>证据完整度及关键机关痕迹不足</small>':''}</button>`).join('')}</div></section>`).join('')}<button class="btn primary" data-action="submit" ${d.suspect&&d.method&&d.motive?'':'disabled'}>给出判断</button></section>`)}
function renderEnd(){const f=s().flags,truth=s().stats.TRUTH>=15,title=f.correct?'月沉，有人拨轮':f.partial?'灯下尚有疑处':'无人答完的诗';shell(`${bg('lake')}<section class="outro"><div class="eyebrow">曲江沉月案 · 夜尽之前</div><h1>${title}</h1><p>${f.correct?'两份调查终于接成一线。主持用沉水香使诗人昏沉，让整块席板短暂没入水中。配重回升后，尸身仍伏在原位；舱外的铜丝扣上门闩。那页将被公开的账，成了杀人的缘由。':f.partial?'主持已被列为首要嫌疑人。两人的调查能够指出谎言，却还不能把手法与动机完整连起来。案卷留下空白，等待下一次核对。':'这一指认未能得到证据支撑。船上仍有人在说谎，案子暂时封卷。两人约定，不能用一个容易的答案换掉死者的一夜。'}</p><p>${f.saved?'幻术师低头看了一眼手腕。那里的红痕，是巡捕将他拉出水舱时留下的。':'幻术师把石屑收进衣袖。他独自脱身的那条暗渠，画在任何一份新城图上都显得多余。'}</p><p>${truth?'水中的楼阁忽然少了一角。两人同时抬头，岸上的飞檐却完好无损。再低头时，灯火已经把缺口填上。':'水中的灯比岸上的灯晚亮了一瞬。风过曲江，涟漪把那点差异带远。'}</p><span class="tag">${f.correct?'完整破案':f.partial?'保留疑点':'错指成案'}</span>${truth?'<span class="tag">共同目击 · 倒影缺角</span>':''}<span class="tag">${s().lead==='A'?'巡捕为起始视角':'幻术师为起始视角'}</span><div class="choice-row"><button class="btn" data-action="notebook">翻阅共同案卷</button><button class="btn primary" data-action="newGame">从另一双眼睛重来</button></div></section>`,truth?'ending-truth':'');}
function notebook(){const shared=s().flags.validated||s().view==='end',ids=shared?s().evidence:s().observations[s().role];return `<p class="help">${shared?'双方已会合，现可核对共同记录。':'这里只收录当前角色亲眼看见、亲耳问到的发现。'}</p><div class="notebook-grid">${ids.length?ids.map(id=>`<article class="evidence-entry">${preview(id)}<h3>${D.clues[id].name}</h3><p>${D.clues[id][s().role]}</p><small class="muted">${s().observations.A.includes(id)?'巡捕已记录　':''}${s().observations.B.includes(id)?'幻术师已记录':''}</small></article>`).join(''):'<p class="help">案卷还没有翻开。先进入画舫调查。</p>'}</div>`}
function progress(){return `<div class="pair-grid">${['A','B'].map(r=>`<div class="pair-column"><h2>${roleName(r)}</h2><p class="help">${s().flags['intro'+r]?'✓':'○'} 独立开场<br>${s().flags['cabin'+r]?'✓':'○'} 船舱勘验<br>${s().flags[r==='A'?'witness':'workshop']?'✓':'○'} ${r==='A'?'船娘问询':'旧图核验'}<br>已记录 ${s().observations[r].length} 项观察</p></div>`).join('')}</div><p class="help">${game.task()}<br>当前角色的选择会改变搭档的追问、机关支援和追逐动作。两份必需调查完成后，在画舫会合验证。</p>`}
function modalHTML(){let title='',body='';if(modal==='notebook'){title='夜行案卷';body=notebook();}if(modal==='progress'){title='一夜，两条路径';body=progress();}if(modal==='help'){title='如何进入这场夜色';body=`<p class="help">开始时选择巡捕或幻术师。地图上的建筑没有文字标牌，移上去会浮起发光；点击进入。金色微光提示当前主线目的地。<br><br>地图右下可切换到搭档。两条线路分别保留自己的调查进度与观察记录，完成后回到画舫互相验证。共同节点会明确提示轮到谁决定。<br><br>调查画面铺满屏幕：按住鼠标或手指左右拖动，松开后点击物件。没有线索圆点，也不提前显示名称。左右方向键和底部滑杆同样可以环视；键盘 Tab 可聚焦物件。<br><br>QTE 先准备、再开始。按提示键或点击动作按钮；每次只判定一个动作，按错或超时会改变结果。打开设置或切离页面会暂停计时。<br><br>返回地图和完成结局时自动保存。此版本是同一设备上的双视角原型，不需要账户或联网。</p>`;}if(modal==='settings'){title='设置与数值';body=`<label class="setting-row"><p>显示开发数值<small>在关键选择和事件后显示实际数值变化</small></p><input type="checkbox" data-setting="debug" ${s().debug?'checked':''}></label><label class="setting-row"><p>舒缓 QTE<small>将每步操作时间延长至 11 秒</small></p><input type="checkbox" data-setting="slowQte" ${s().slowQte?'checked':''}></label>${s().debug?Object.entries(s().stats).map(([k,v])=>`<div class="stat"><span>${k}</span><div class="stat-meter"><i style="width:${k==='EVIDENCE'?v*10:v}%"></i></div><span>${v}</span></div>`).join('')+'<p class="help">TA：巡捕对幻术师的信任；TB：幻术师对巡捕的信任。<br>TRUTH：真相度；DREAM：依恋；CHAOS：失稳；EVIDENCE：证据完整度。</p>':''}<button class="quiet" data-action="newGame">重新选择身份</button>`;}if(modal==='restart'){title='另起一夜';body='<p class="help">重新开始会替换这次的本地地图存档。</p><button class="btn primary" data-action="confirmNew">重新选择身份</button>';}
return `<div class="modal" role="dialog" aria-modal="true" aria-label="${title}"><div class="modal-card"><div class="modal-head"><h2>${title}</h2><button class="quiet" data-action="close" aria-label="关闭">×</button></div>${body}</div></div>`;}
function openModal(id){lastFocus=document.activeElement;modal=id;render();}
app.addEventListener('click',e=>{
 const el=e.target.closest('[data-action],[data-role],[data-location],[data-choice],[data-object],[data-match-id],[data-deduce]');if(!el)return;
 if(el.dataset.object){if(e.detail===0)collect(el.dataset.object);return;}
 if(el.dataset.role){game=new Game();game.setRole(el.dataset.role);panScene='';render();return;}
 if(el.dataset.location){game.location(el.dataset.location);render();return;}
 if(el.dataset.choice!==undefined){const before={...s().stats};game.advance(+el.dataset.choice);render();effectToast(before);return;}
 if(el.dataset.matchId){s().match[el.dataset.matchRole]=el.dataset.matchId;render();return;}
 if(el.dataset.deduce){s().deduction[el.dataset.deduce]=el.dataset.value;render();return;}
 switch(el.dataset.action){
 case 'notebook':case 'settings':case 'help':case 'progress':openModal(el.dataset.action);break;
 case 'close':modal=null;render();break;
 case 'resume':{const saved=readSave();if(saved){game=new Game(saved);modal=null;panScene='';render();}break;}
 case 'newGame':openModal('restart');break;
 case 'confirmNew':game=new Game();modal=null;panScene='';stepToken='';try{localStorage.removeItem(SAVE)}catch{}render();break;
 case 'switch':game.switchRole();s().insight=null;render();break;
 case 'meet':game.location('boat');render();break;
 case 'finishInvest':if(game.finishInvest())render();else toast(s().scene==='water'?'先核对铜轮和止水绳，再触动机关。':s().role==='A'?'桌边还缺一项可以带回核对的痕迹。':'先检查门闩，确认牵线能否从舱外通过。');break;
 case 'dismissInsight':s().insight=null;render();break;
 case 'panLeft':pan=Math.max(0,pan-.15);layoutPan();break;
 case 'panRight':pan=Math.min(1,pan+.15);layoutPan();break;
 case 'validate':{const before={...s().stats};if(game.validate()){render();effectToast(before);}else toast('这两项暂时接不上。试着将物理痕迹与门闩的机关路径核对。');break;}
 case 'beginQte':s().view='qte';stepToken='';render();break;
 case 'hitQte':resolveQte(true);break;
 case 'submit':{const before={...s().stats};if(game.submit()){render();effectToast(before);}break;}
 }
});
app.addEventListener('input',e=>{if(e.target.id==='panRange'){pan=+e.target.value/1000;layoutPan();}});
app.addEventListener('change',e=>{if(e.target.dataset.setting){s()[e.target.dataset.setting]=e.target.checked;render();}});
document.addEventListener('keydown',e=>{
 if(modal){if(e.key==='Escape'){modal=null;render();}if(e.key==='Tab'){const nodes=[...app.querySelectorAll('.modal button,.modal input')].filter(x=>!x.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}
 if(e.repeat)return;
 if(s().view==='qte'&&['a','d','w'].includes(e.key.toLowerCase())){e.preventDefault();resolveQte(e.key.toUpperCase()===game.qteSteps()[s().qte.step][1]);return;}
 if(s().view==='investigate'&&['ArrowLeft','ArrowRight'].includes(e.key)&&e.target.type!=='range'){e.preventDefault();pan=Math.max(0,Math.min(1,pan+(e.key==='ArrowLeft'?-.08:.08)));layoutPan();}
 const l=e.target.closest?.('[data-location]');if(l&&['Enter',' '].includes(e.key)){e.preventDefault();game.location(l.dataset.location);render();}
});
window.addEventListener('resize',layoutPan);
// Begin loading the art used immediately; other scene images load on first visit.
['lake','boat','cabin','water'].forEach(id=>{const i=new Image();i.src=sceneImage(id)});
render();
})();
