const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const D=require('../data.js'),Game=require('../core.js');
function drain(g,choice=0){let count=0;while(g.s.view==='dialog'){assert.ok(++count<60,'Dialogue must finish');g.advance(Math.min(choice,(g.currentLine().choices?.length||1)-1));}}
function localRoute(g,choice){g.location('boat');assert.equal(g.s.view,'investigate');for(const id of ['cup','poem','latch','footprints'])g.collect(id);assert.equal(g.finishInvest(),true);g.location(g.s.role==='A'?'shrine':'academy');drain(g,choice);assert.ok(g.routeDone(g.s.role));}
function play(lead,choice,qtePass,extra=true){const g=new Game();g.setRole(lead);drain(g,choice);assert.equal(g.s.view,'map');g.location('boat');drain(g,choice);localRoute(g,choice);assert.equal(g.readyToMeet(),false);g.switchRole();drain(g,choice);localRoute(g,choice);assert.ok(g.readyToMeet());
 if(extra){for(const id of ['books','incense','apricot','lake','bell','dock','tavern']){g.location(id);drain(g,choice);}}
 const before=g.s.stats.TRUTH;g.location('apricot');drain(g,choice);if(extra)assert.equal(g.s.stats.TRUTH,before,'Repeated visits must not farm truth');
 g.location('boat');drain(g,choice);assert.equal(g.s.view,'match');g.s.match={A:'testimony',B:'model'};assert.equal(g.validate(),false);g.s.match={A:'poem',B:'latch'};assert.equal(g.validate(),true);drain(g,choice);assert.equal(g.s.scene,'water');assert.equal(g.finishInvest(),false);g.collect('gear');g.collect('rope');g.collect('channel');g.finishInvest();drain(g,choice);assert.equal(g.s.view,'qteReady');g.s.view='qte';for(let i=0;i<3;i++)g.qteResult(qtePass);drain(g,choice);assert.equal(g.s.view,'qteReady');assert.equal(g.qteSteps()[0][0],lead==='A'?'跃过松动桥板':'将月光引向安全的桥板');g.s.view='qte';for(let i=0;i<3;i++)g.qteResult(qtePass);drain(g,choice);assert.equal(g.s.view,'deduce');g.s.deduction={suspect:'host',method:'mechanism',motive:'ledger'};assert.ok(g.submit());assert.equal(g.s.view,'end');assert.equal(g.s.flags.correct,true);for(const [key,val] of Object.entries(g.s.stats))assert.ok(val>=0&&val<=(key==='EVIDENCE'?10:100));return g;
}
for(const role of ['A','B'])for(const choice of [0,1])for(const pass of [true,false]){const g=play(role,choice,pass);assert.equal(g.s.flags.saved,choice===0);assert.equal(g.s.flags.chaseSuccess,pass);console.log('PASS route',role,'choice',choice,'QTE',pass?'success':'failure');}
const t=new Game();t.s.view='investigate';t.s.scene='cabin';t.collect('cup','A');const score=t.s.stats.EVIDENCE;t.collect('cup','A');t.collect('cup','B');assert.equal(t.s.stats.EVIDENCE,score,'A shared physical clue must not score twice');
for(const [id,c] of Object.entries(D.clues)){assert.ok(fs.existsSync(path.join(__dirname,'../assets/scenes',c.scene+'.png')));if(c.x!==undefined){assert.equal(Game.hitTest(c.scene,c.x,c.y),id);assert.equal(Game.hitTest(c.scene,-1,-1),null);assert.ok(c.x-c.w/2>=0&&c.x+c.w/2<=1&&c.y-c.h/2>=0&&c.y+c.h/2<=1);}}
// Render-smoke checks execute the page renderer without a browser or network.
const htmlApp={innerHTML:'',addEventListener(){},querySelector(){return null},querySelectorAll(){return []}};
const context={console,Game,GAME_DATA:D,performance:{now:()=>0},Image:class{},localStorage:{getItem(){return null},setItem(){},removeItem(){}},requestAnimationFrame:()=>0,cancelAnimationFrame(){},setTimeout:()=>0,clearTimeout(){},document:{getElementById:id=>id==='app'?htmlApp:null,querySelector:()=>null,addEventListener(){},hidden:false},addEventListener(){}};context.window=context;vm.createContext(context);
let source=fs.readFileSync(path.join(__dirname,'../script.js'),'utf8');source=source.replace('render();\n})();','window.testUI={set:g=>{game=g},render,modal:m=>{modal=m}};render();\n})();');vm.runInContext(source,context);
const rg=play('B',0,true);for(const view of ['start','map','dialog','investigate','match','qteReady','qte','deduce','end']){if(view==='dialog')rg.enter('witness');rg.s.view=view;rg.s.scene=view==='investigate'?'cabin':rg.s.scene;if(view.startsWith('qte'))rg.s.qte={type:'water',step:0,success:0};context.testUI.set(rg);context.testUI.render();assert.ok(htmlApp.innerHTML.includes('<main'));assert.ok(!htmlApp.innerHTML.includes('undefined'),'No undefined copy in '+view);if(view==='map'){assert.equal((htmlApp.innerHTML.match(/data-location=/g)||[]).length,12);assert.ok(!htmlApp.innerHTML.includes('<title>'));}if(view==='investigate'){assert.ok(!htmlApp.innerHTML.includes('发光热点'));assert.equal((htmlApp.innerHTML.match(/data-object=/g)||[]).length,4);}console.log('PASS render',view);}
for(const modal of ['notebook','settings','help','progress','restart']){context.testUI.modal(modal);context.testUI.render();assert.ok(htmlApp.innerHTML.includes('role="dialog"'));console.log('PASS modal',modal);}
console.log('All route, hit-area, duplicate-reward and renderer checks passed.');
